### ISSUE TITLE
[Automation - BUG] Automation center app Active flow session Trace shows Null Projects

### ISSUE THREAD

**Issue by maru55** [microsoft/powercat-automation-kit#100]
### Describe the issue

I have created 4 projects in Automation project, i approved them as well, but still i am not able to see them inside Active flow session Trace, i have mapped them as well inside automation center  setup
![image](https://user-images.githubusercontent.com/37395784/203566533-057bf9b7-24f1-4c6b-9ab4-e0346ba2d3f7.png)
![image](https://user-images.githubusercontent.com/37395784/203702053-bfada7cf-bfc7-42b0-a5a8-95abc1a0439e.png)

### Expected Behavior

it should display what ever projects i have submitted in Automation project

### What component are you experiencing the issue with?

Automation Center

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

Automation center App

### Steps To Reproduce

create a project in automation project
Submit it
Approve it in Teams
Open Automation center app.

**Comment by KoteshMCGit** [comment]
looking into the issue and will update soon
