### ISSUE TITLE
[Automation - BUG]ROI Calculator flow fails

### ISSUE THREAD

**Issue by nbetters** [microsoft/powercat-automation-kit#116]
### Describe the issue

When flow runs, if the calculated ROI seems to be to low the flow fails (at leas this is the only time I notice the flow failing and not providing an ROI).

Even if the ROI is negative, it should calculate and display, there are business cases where an automation should be developed for quality, employee moral etc. 

I should note, we have added fields to the form, but none of the ROI basis fields were edited.
![image](https://user-images.githubusercontent.com/55587135/208158089-64d128e2-d123-4a83-9713-51a77af588d7.png)
![image](https://user-images.githubusercontent.com/55587135/208158114-81dd84e4-2d0b-4708-ae00-031b1baec4f8.png)

### Expected Behavior

ROI should calculate both positive and negative numbers

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

1.0.20220913.3

### What app or flow are you having the issue with?

AutomationKit- AutomationCOEMain

### Steps To Reproduce

Create project
Use low frequency, low expenses

**Comment by KoteshMCGit** [comment]
Analysis is in progress

**Comment by KoteshMCGit** [comment]
As per your screen shot , few values are not showing. As per available screen values, could not able to reproduce the error. I think it is good to connect once to look at the issue.

**Comment by KoteshMCGit** [comment]
As per screen shot , you have created new process frequency as "Yearly" and new Processing Peeks as "Yearly". could you please provide me what is score value you have given to those new process frequency and Processing Peeks. As per design, it supports only for Daily, Hourly, Weekly, monthly and quarterly. I am thinking issue could be with this newly created process frequency "yearly" processing. could you please try with daily/weekly/monthly/quarterly with same ROI values.

**Comment by nbetters** [comment]
Both are set at "1", having Yearly should be mandatory, there are hundreds of automations just in finance that have to be run at the tail end of every year that are finance related (taxes etc). For the mean time I could change the score to quarterly and perhaps that will be a work around?

Thanks!

**Comment by nbetters** [comment]
> As per screen shot , you have created new process frequency as "Yearly" and new Processing Peeks as "Yearly". could you please provide me what is score value you have given to those new process frequency and Processing Peeks. As per design, it supports only for Daily, Hourly, Weekly, monthly and quarterly. I am thinking issue could be with this newly created process frequency "yearly" processing. could you please try with daily/weekly/monthly/quarterly with same ROI values.

I confirmed it does work on quarterly, however the process is required to be done once annually so if I mark it quarterly I then need to divide the values out manually and that will confuse the department heads

**Comment by nbetters** [comment]
![image](https://user-images.githubusercontent.com/55587135/210412988-e54da871-82ee-471b-94e4-232d92950b2e.png)

**Comment by KoteshMCGit** [comment]
As per design, ROI will be calculated based on Process Time, cost and frequency + remediation cost. if you change process time or cost, ROI will be recalculated.
 
Please note that with-in specific process time (duration), each BOT can process different volume of records/transactions. And also as per design, we don't have any option /configuration to recognize / identify actual volume from the bot run / failure. So volume will not be considered in ROI. hence ROI is calculated based on the process time and cost.

**Comment by nbetters** [comment]
It should not be calculating negative ROI, even when I change the development cost to $1 for something that should have an ROI of hundreds of thousands, it returns a negative ROI

**Comment by KoteshMCGit** [comment]
we are unable to reproduce with negative ROI. can you please share respective screen shots like project details, PB dash board along with respective formula/query expr details.

**Comment by nbetters** [comment]
I am using the current version of the power BI directly from git hub, I am attaching the physical file here as well.


  *   I have to make a modification to the powerbi fails if there is no completed date (this is a miss in my opinion, there could be long running processes that have start dates, overall status of pending and are not complete yet)

***@***.***
In the attached file I have NOT made this change.

The first time the report loads it looks like this
***@***.***
After "fixing" the fields there are usually blank cards still not populating
***@***.***

Now onto the project ROI issue
I took a video of the PBI, as well as the project, there is no way this project should be generating a negative actual savings. The human time its saving is immense. (again I have NOT adjusted the PBI code)...
You can see in the PBI the completed on date is not calculating correctly, however this is a system date field not free text so the syntax in PBI must be wrong. (our data analytics team member looked at this and agreed)
https://www.screencast.com/t/cppEYw9rj

***@***.***

**Comment by KoteshMCGit** [comment]
for pending status records, I have updated my comments in https://github.com/microsoft/powercat-automation-kit/issues/126 , please do verify once and let me know if you need any additional clarifications.

**Comment by KoteshMCGit** [comment]
We have fixed the issue for respective flow, while using zero ROI calculation for pending tickets/creating or selecting of an new option yearly processing frequency.
