### ISSUE TITLE
[Automation - BUG] Unable to import satellite solution as user that is not Key Vault Owner

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#123]
### Describe the issue

When attempting to import the Satellite solution as a user that is now an owner that the import will fail with message similar to

Could not verify the user permission on '/subscriptions/12345678-1234-1234-1234-123456789abc/resourceGroups/AutomationKit-Test/providers/Microsoft.KeyVault/vaults/testkeyvault' resource. Make sure that Microsoft.PowerPlatform provider is registered in the Azure subscription.

### What component are you experiencing the issue with?

Other

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Create a new solution
2. Add an Environment Variable of type secret
3. Choose secret store of type Azure Key Vault
4. Add a new Azure Key Vault secret reference
5. Enter the Azure Subscription Id that contains the Azure Key Vault
6. Enter the Resource Group Name that the Azure Key Vault belongs to
7. Enter the name of the Azure Key Vault
8. Enter the name of the Secret you want to connect to

**Comment by Grant-Archibald-MS** [comment]
To connect to environment variables of type secret the following needs to apply
1. The user account must not be a Business-to-Business (B2B) Guest account
2. The user must be assigned a minimum role of Key Vault Secret User
3. The Azure Subscription must belong to the same Azure Active Directory tenant

The user could also be assigned a role of contributor or owner of the Key Vault

**Comment by Grant-Archibald-MS** [comment]
Updated the December setup notes to mention minimum permissions of Key Vault Secret User to the importing user

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.
