### ISSUE TITLE
[Automation Kit - QUESTION] Where can I find most recent solution file

### ISSUE THREAD

**Issue by nbetters** [microsoft/powercat-automation-kit#127]
### What is your question?

Hello, I am trying to update our automationKit and cannot find the solution file in github? I do not have the ability to command line install due to my organizations security policies, I must upload the new solution to the powerapps admin portal to update it.

### What component is the question related to?

Automation Solution Manager

### What app or flow are you having the issue with?

finding newest solution files

**Comment by KoteshMCGit** [comment]
you can find the latest solution from dec 2022 release in github or find below URL to follow Dec 2022 release notes.

https://github.com/microsoft/powercat-automation-kit/releases/tag/AutomationKit-December2022
