### ISSUE TITLE
[Automation Kit - QUESTION] Clarifying how ROI is calculated

### ISSUE THREAD

**Issue by nbetters** [microsoft/powercat-automation-kit#128]
### What is your question?

I am having a hard time understanding what is driving the ROI calculations, per my screen shot simple math should account for aprx. a $12k ROI, I understand the complexity score and maintenance etc affect this, but the system is calculating a $1,220 ROI, whish is10k too low.

If an employee is saving 5 minutes per transaction and has to process 20 transactions a day, that is a huge amount of time savings so the ROI should be significantly higher 
![image](https://user-images.githubusercontent.com/55587135/211092389-a862e9b9-b7f3-44f0-b0fa-057c53f7fe71.png)

I watched the end to end submission of a project video found here https://www.youtube.com/watch?v=CB91k3IhRCI
and the presenter does not define what the values of each field mean, this would be helpful.

### What component is the question related to?

Automation Project

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

automation project ROI calculation

**Comment by KoteshMCGit** [comment]
Analysis is in progress.

**Comment by KoteshMCGit** [comment]
Please find the below of our analysis details.

As per ROI flow design, ROI will be calculated as per below screen shot, which is available in your Power BI dashboard (Last page "ROI calculations"):

![image](https://user-images.githubusercontent.com/107620140/212333916-d5b117a4-cfe0-43a7-9cf6-b0510e53b644.png)

Analysis notes:
1. As per your screen shot, you have provided 256 as No of working days per year. But flow is considering 251 as hard coded value and calculating. we have created an issue https://github.com/microsoft/powercat-automation-kit/issues/131 and working on this. 
2. As per Flow Design, Process Peek score will not be considered in ROI calculations. End user will provide average transactions /volume for process frequency.
3. As per your screen shot, you did not consider the rework effort and respective cost in ROI calculation.

**Comment by nbetters** [comment]
It is calculating negative savings, which it should never have

**Comment by KoteshMCGit** [comment]
can you please provide more details like automation project with negative ROI. so that we will do further analysis.

**Comment by nbetters** [comment]
thats the problem, there is not a project which would have a negative ROI..

I believe there is a bigger issue here, I dug into the lines in the bi report to try and establish why BI would not be calculating and I found rows of data in the dataverse that are NOT showing in the bi table. See this screenshot I do not have any filters applied and the report was refreshed 3 times for certainty. 

![image](https://user-images.githubusercontent.com/55587135/213181876-cbf3896a-d97c-4e54-8852-0bc7b807bcf0.png)

**Comment by nbetters** [comment]
![image](https://user-images.githubusercontent.com/55587135/213213131-4fd6b314-27db-4853-88af-d17497b401fb.png)

**Comment by KoteshMCGit** [comment]
Today we have tried to reproduce the above observation with your values. But we could not able to reproduce. 

Please find the below screenshot for the same
![image](https://user-images.githubusercontent.com/107620140/213736578-26e0394a-2c79-404e-9335-e4bc6354d8af.png)

total savings are calculated as below.

for success session = cost per instance + cost per head 
for canceled session = 0 
rest of other sessions (errors/ failed) = overhead cost + cost to remediate per instance

**Comment by KoteshMCGit** [comment]
Please do verify for all records are coming from table automation project in dashboard from main environment.

screenshot of automation project table on dashboard.
![image](https://user-images.githubusercontent.com/107620140/215730231-36f1598c-8259-42bd-add3-2c7afe1a951c.png)

If all records are not coming, please publish that table in main environment once and try to configure dashboard once.

**Comment by nbetters** [comment]
The table is published to the environment, and I am not seeing any missing data or errors in the columns. The only thing that looks off is the "Project Status" column is blank for any project that is approved?

***@***.***
