### ISSUE TITLE
[Automation - BUG] PowerBI reporting Succeeded transactions in the "Failure" dashboard

### ISSUE THREAD

**Issue by nbetters** [microsoft/powercat-automation-kit#129]
### Describe the issue

The "Failure Rat by Type for all flows" card in the Power BI report is calculating succeeded transactions not failures/faults
![image](https://user-images.githubusercontent.com/55587135/211385623-2a0eceb9-02c1-45c3-9874-fa8d14ca54fb.png)
Here are the traces
![image](https://user-images.githubusercontent.com/55587135/211385927-0249c59d-8186-4e01-88ec-194ac494e2c3.png)

### Expected Behavior

Calculate faulted transactions against successes

### What component are you experiencing the issue with?

Power BI dashboard

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

AutomationKit power bi

**Comment by KoteshMCGit** [comment]
Analysis is in progress.

**Comment by KoteshMCGit** [comment]
can we connect once to discuss on ROI clarifications and Power board dashboard observations. please ping me kmarram@microsoft.com in teams.

**Comment by KoteshMCGit** [comment]
As per our analysis, it is not considering as error. it is a part of grouping all the process statuses. As per your screen shot , you dont have any failed processes.

for Analysis purpose, we have made some test data and find the below screen shot for your reference. you can find all error codes along with success status for all flow runs from flow session trace table.

screenshot

![image](https://user-images.githubusercontent.com/107620140/213703383-26f39a27-9a3e-4903-baf0-8608bff98722.png)

**Comment by KoteshMCGit** [comment]
As per issue description, we have clarified to you and closing now. If you feel it is not cleared to you. pls let us know.

**Comment by mikefactorial** [comment]
@nbetters This has been fixed in the latest release.
