### ISSUE TITLE
[Automation Kit - Feature]: Monitor more than one Cloud Flow in a solution

### ISSUE THREAD

**Issue by jpad5** [microsoft/powercat-automation-kit#130]
### Is your feature request related to a problem? Please describe.

There are cases where there are multiple cloud flow triggers in an automation solution and currently Automation Kit doesn't allow monitoring those cloud flows.

### Describe the solution you'd like

Able to meter multiple cloud flows in the automation solution

### Additional context?

![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/94862471/211614163-7373506b-21fe-4f0d-970c-4eb0bdfa9ef5.png)

**Comment by KoteshMCGit** [comment]
we have implemented of metering multiple cloud flows in a solution. Please note that ROI will be calculated with using of all metered cloud flows in a solution.

**Comment by mikefactorial** [comment]
@jpad5 This has been fixed in the latest release.
