### ISSUE TITLE
[Automation - BUG] Observed ROI calculation is happening with hard coded Process frequency values 

### ISSUE THREAD

**Issue by KoteshMCGit** [microsoft/powercat-automation-kit#131]
### Describe the issue

When ROI flow runs, it is considering hard coded process frequency values for No of working days per year. and flow is considering hard coded value 251 days per year instead of automation project record. Because of this, ROI is not calculated as per user requirement.

Example of automation project record with 260 working days per year. But flow will consider as 251 instead of below project record.

![image](https://user-images.githubusercontent.com/107620140/212326465-e6cca4b2-8dea-45e2-90b2-f1d109c86ffc.png)

As per ROI flow / App design, it is considering hardcoded values for process frequency like hourly/daily/weekly/monthly/ quarterly and yearly.

### Expected Behavior

ROI calculations should happen from automation project record values instead of hard coded process frequency values No of working days per year, hourly/daily/monthly/quarterly and yearly. Otherwise provide an option to modify the default values. so that ROI calculation will be based on user defined values instead of hard coded values.

### What component are you experiencing the issue with?

Cloud flows

### What solution version are you using?

1.0.20220913.3

### What app or flow are you having the issue with?

Calculate ROI Saving Potential for Automation Project

### Steps To Reproduce

1. Create project with below values
2. Give 255 as No of working days per year
3. Select Process frequency as "Daily"
4. And provide your own values to all other fields
validate the ROI. It will be calculated for 251 instead of of 255 working days per year.

### Anything else?

Analysis and Fix: 
We are going to modify the flow and provide an environment variable "autocoe_DefaultFrequencyValues" to provide all process frequency values in json format. Below is json format to modify / update user defined Process frequency values.

Please note that below values are default values for Environment variable "autocoe_DefaultFrequencyValues". End user can modify these values.

Format:
{"processfrequency":{"hourly":2008,"daily": 251,"weekly": 52,"monthly": 12,"quarterly": 4,"yearly": 1 } }

screen shot of Environment variable:

![image](https://user-images.githubusercontent.com/107620140/212327901-5149115d-cf40-4740-b8a2-f05f5603e499.png)

Important Note:
After changing / modifying the values, end user has to turn off and turn on the cloud flow "Calculate ROI Saving Potential for Automation Project" to consider for updated values. Otherwise flow will consider previous values.

**Comment by KoteshMCGit** [comment]
End user can utilize this default configurations like below format in ROI calculation.

Format:
{"processfrequency":{"hourly":2008,"daily": 251,"weekly": 52,"monthly": 12,"quarterly": 4,"yearly": 1 } }

for Daily Frequency:
User can set "Working days per year" in Automation project records and the same value will be used to calculate ROI. if you provide 0 (zero) days per year, ROI will be calculated with same zero value. so ROI will be zero to that Automation project. You can set to zero, if you would like to exclude from ROI for that project.

for Hourly Frequency:
it is the value for No of working hours per year. user can modify / change this default value (2008) to their desired value to calculate ROI.

for Weekly Frequency:
it is the value for No of working weeks per year. user can modify / change this default value (52) to their desired value to calculate ROI.

for monthly Frequency:
it is the value for No of months per year. user can modify / change this default value (12) to their desired value to calculate ROI.

for Quarterly Frequency:
it is the value for No of quarters per year. user can modify / change this default value (4) to their desired value to calculate ROI.

for yearly Frequency:
User can modify / change this default value (1) to their desired value to calculate ROI.

**Comment by KoteshMCGit** [comment]
Issue has been fixed and validated.

**Comment by mikefactorial** [comment]
@KoteshMCGit This has been fixed in the latest release.
