### ISSUE TITLE
[Automation Kit] Add new project button is missing in Automation Project canvas app

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/powercat-automation-kit#134]
### What is your question?

Add new project button is missing in Automation Project canvas app

### What component is the question related to?

Automation Project

### What solution version are you using?

latest

### What app or flow are you having the issue with?

Automation Project

**Comment by KoteshMCGit** [comment]
It seems current logged user is not having sufficient permissions to create Automation Projects on respective environment.

Could you please verify the current logged user should have at-least any one of below mentioned security roles in respective environment.

1. Automation Project Admin 
or
2. Automation Project Contributor

**Comment by ApoorvaKantale** [comment]
I do have both the roles

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: KOTESWARA RAO MARAM ***@***.***>
Sent: Tuesday, January 17, 2023 5:00:31 PM
To: microsoft/powercat-automation-kit ***@***.***>
Cc: Apoorva Kantale (g) ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/powercat-automation-kit] [Automation Kit] Add new project button is missing in Automation Project canvas app (Issue #134)


It seems current logged user is not having sufficient permissions to create Automation Projects on respective environment.

Could you please verify the current logged user should have at-least any one of below mentioned security roles in respective environment.

  1.  Automation Project Admin
or
  2.  Automation Project Contributor

**Comment by ApoorvaKantale** [comment]
Im the admin, I have both roles assigned to my account, but still not able to see add new project button 

![image](https://user-images.githubusercontent.com/78148795/212948418-edb48659-9663-48fe-8ae6-0f69b8cfa13d.png)

**Comment by KoteshMCGit** [comment]
can you please share the screenshot for above security roles assignment to your account. 

Please ensure that user should be assigned to directly security group. Earlier we have observed one of our Customer is assigned to security group through Dataverse team (O365 group) instead of direct assignment.
 
As per design, application will work with direct assignment only.

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/212962649-3b35d51a-19c6-410e-a49c-ef650bd8411f.png)


I have assigned the role correctly, but if you have any documentation, let me cross check with it can you please share the documentation

**Comment by KoteshMCGit** [comment]
could you please refer the below documentation ("Assign security roles") section and ensure to assign in power platform admin center.

https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/setup/main

**Comment by ApoorvaKantale** [comment]
Hi,

It is assigned correctly the roles in power platform admin center.
Can you please help me to fix the issue on priority

Thanks in advance

**Comment by KoteshMCGit** [comment]
can we connect once to verify the issue. please ping me in teams kmarram@microsoft.com

**Comment by ApoorvaKantale** [comment]
Sure, We can I have pinged already

**Comment by ApoorvaKantale** [comment]
Hi Kotesh,

Any Update on the above issue, Please help on this on priority.

**Comment by KoteshMCGit** [comment]
can we connect once to verify the issue.

**Comment by KoteshMCGit** [comment]
As per our analysis, it could happen due to below configuration might not set for main and satellite environments.

can you verify the below of configurations on both main and satellite environments. if it is not enabled, please delete main and satellite solutions and enable (set to true) the below setting in power platform admin page for both environments.

![image](https://user-images.githubusercontent.com/107620140/220104799-b3794157-4d17-40af-acfa-b02cb82f2120.png)

After enabling of above option, please install main and satellite solutions. you will get new project creation button and other buttons.

**Comment by ApoorvaKantale** [comment]
Hi,

I have already enabled this option in both environments before installations

**Comment by KoteshMCGit** [comment]
can you please ping me kmarram@microsoft.com in Teams to connect and verify the issue.

**Comment by paulkpwong** [comment]
Hi, 
I have the same issue, could you help to check too?

**Comment by KoteshMCGit** [comment]
can you please ping me [kmarram@microsoft.com](mailto:kmarram@microsoft.com) in Teams to connect and verify the issue in IST time

**Comment by ApoorvaKantale** [comment]
Hi Kotesh,

Any Update on the above issue, Please help on this on priority.

**Comment by Grant-Archibald-MS** [comment]
@ApoorvaKantale looking at this issue the specific code for access to this button in [Ideas Dashboard](https://github.com/microsoft/powercat-automation-kit/blob/main/AutomationCoEMain/SolutionPackage/src/CanvasApps/src/autocoe_automationproject_f233b/Src/scr_IdeasDashboard_CK.fx.yaml) where on line 18 is sets the isProjectAdmin variable that is used to enabled the menu button.

Once possible issue could be a difference in the case for User().Email and the User 'Primary Email' value or a difference between the UPN and the Primary email. I can see similar UPN vs Email in thread [User-Email-display-UPN-value-not-Emai](https://powerusers.microsoft.com/t5/Building-Power-Apps/User-Email-display-UPN-value-not-Email/td-p/184651) 

To help further diagnose the issue would you be able to create a new solution and Canvas application. Add a label with the value of LookUp([@'Security Roles'], Name = "Automation Project Contributor",Role) in Concat(LookUp([@Users],'Primary Email' = User().Email).'Security Roles (systemuserroles_association)',Role & ";") and determine if the value is true or false.

**Comment by ApoorvaKantale** [comment]
Hi, 

Thank for the detailed explanation.

Yes, I do see a difference in my UPN and Email ID, may be that is reason . I might be facing the issue

**Comment by Grant-Archibald-MS** [comment]
@KoteshMCGit I will review the changes and look at adding unit tests to verify differences between switching to Set(currentUserEmail,Lower(Office365Users.MyProfile().Mail)); and Lower('Primary Email') = currentUserEmail rather than using the User().Email

**Comment by Grant-Archibald-MS** [comment]
@ApoorvaKantale thanks for the feedback, I have a local version that changes the Email comparision. I am in the process of testing those changes with different test cases for permissions and email values.

Once these changes have been reviewed and approved we will look to update the releases with the changes. At the moment the next release is due for Wednesday next week (3rd of May). I will update this issue as testing proceeds and look to see if we can include this change as part of the May milestone release

**Comment by ApoorvaKantale** [comment]
Thank you so much :)

**Comment by ApoorvaKantale** [comment]
Hi,

Now I have changed my UPN and Email, Both the values are same now

But still I'm facing the issue, Still unable to add project button

**Comment by ApoorvaKantale** [comment]
Is it case sensitive as well ?

**Comment by Grant-Archibald-MS** [comment]
@ApoorvaKantale yes it is case sensitive today. I will create some sample Power Fx commands here so that you can test values.
