### ISSUE TITLE
[Automation Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by shanjaf** [microsoft/powercat-automation-kit#136]
### What is your question?

where can i find autocoe_desktopflowactions.csv file?

### What component is the question related to?

Automation Solution Manager

**Comment by KoteshMCGit** [comment]
you can find the file from below link.

https://github.com/microsoft/powercat-automation-kit/releases/download/AutomationKit-September2022/autocoe_desktopflowactions.csv

**Comment by KoteshMCGit** [comment]
we have shared the respective file and closing this item. Please let us know if you have any questions on this item.

**Comment by mikefactorial** [comment]
@shanjaf This has been fixed in the latest release.
