### ISSUE TITLE
[Automation - BUG] AutomationCOE Power BI dashboard is not loading

### ISSUE THREAD

**Issue by tiyasasarkar** [microsoft/powercat-automation-kit#138]
### Describe the issue

We are trying to open the Power BI template inside AutomationKitInstall folder using Power BI desktop but after giving Main Environment URL (in the same format mentioned [organization].crm[N].dynamics.com), it is not getting loaded with the attached error. 
<img width="382" alt="AutomationCOE dashboard error" src="https://user-images.githubusercontent.com/123467998/214306162-cb78226a-f147-41b9-a110-4fe4f3b30ce4.png">

### What component are you experiencing the issue with?

Power BI dashboard

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

NA

### Steps To Reproduce

1. Opening the Power BI template (file name: Automation.Kit.V1.0.20220914.pbit) inside AutomationKitInstall folder using Power BI Desktop.
2. Providing the Main Environment URL in the mentioned format ([organization].crm[N].dynamics.com).
3. The data was loading and after few mins got the attached error.
<img width="382" alt="AutomationCOE dashboard error" src="https://user-images.githubusercontent.com/123467998/214307468-c6105563-9581-47e9-9aa1-7ebf1743b08e.png">

**Comment by KoteshMCGit** [comment]
As per above screenshot, we are unable to find exact issue details. could you please scroll down and find the exact issue details. and let me know the exact url (without your organization in url) , which you have provided to power BI dashboard.

we request you to re-configure once and incase issue occurs again, please share the screenshot of exact error details.

**Comment by KoteshMCGit** [comment]
please verify are there any columns are showing as Error something like below screen shot.

![image](https://user-images.githubusercontent.com/107620140/216900642-174ae361-c608-480a-be6a-497a53015400.png)

Please share more details like logs/ like above screen shot to do further investigation.

**Comment by tiyasasarkar** [comment]
We didn't make any changes but the dashboard is loading now.

**Comment by KoteshMCGit** [comment]
As per your comment, issue has been resolved and closing now.

**Comment by mikefactorial** [comment]
@tiyasasarkar This has been fixed in the latest release.

**Comment by maheshnav** [comment]
I faced similar issue cause due to multiple inactive and active record for solutioning metering table in Main environment if you try to activate or configure same project again. By deleting inactive record or one or both the record and reconfigure the artifacts it works again.
