### ISSUE TITLE
[Automation - BUG] Automation Project Viewer role is not able to open Automation Project App to approve requests

### ISSUE THREAD

**Issue by tiyasasarkar** [microsoft/powercat-automation-kit#139]
### Describe the issue

We have deployed AutomationKit using COE admin account and provided me the Automation Project Viewer role (Along with Environment Maker role because without this user was not able to access the environment). So I set myself as fallback approver and when an automation project comes to me for approval I was not able to open the Automation Project app from the View Details link. I got the attached error.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/123467998/214310625-dd43628c-f747-472d-a035-74f9e4650fc3.png">

### Expected Behavior

As an approver with Automation Project Viewer role, should be able to access Automation Project app to see the project details in view mode.

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Automation Project

### Steps To Reproduce

1. After deploying the AutomationKit Main solution to the Main environment, configured the security roles and provided myself the Automation Project Viewer role (Along with Environment Maker role because without this user was not able to access the environment).
2. In Automation Center App I was set as fallback approver, so if an Automation Project was submitted for approval which was not having business owner, comes to me for approval.
3. Before approving I tried to click on View Details link which redirected me to Automation Project App (because as per document Approver/Business Owner with Viewer role should be able to see the project details in view mode) but the app was not opening. (attached screenshot). Also not able to see the Automation Project App in Main environment from my account (having Viewer role).
<img width="949" alt="image" src="https://user-images.githubusercontent.com/123467998/214312776-a698add5-d22a-4eee-8fc3-62e60e6ab8f8.png">

**Comment by KoteshMCGit** [comment]
As per our analysis, It is not security role issue. It is access issue for app. Please request respective COE Admin to provide Access / share with you as co-owner.

**Comment by KoteshMCGit** [comment]
As per our analysis, It is not security role issue. It is access issue for app. 

Please request respective COE Admin to provide Access / share with you as co-owner/user.

Please find the below link for more details on canvas app sharing.
https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/share-app

Please verify run / play once the respective canvas app, after sharing with you. Once canvas app is shared with you , you can play from solution / power apps/email link.

**Comment by KoteshMCGit** [comment]
As per issue, we have provided solution. Please do verify once and let us know, if you still observe the issue. Otherwise, we can close the issue.

**Comment by tiyasasarkar** [comment]
Yes it worked. Thanks. We are good to close the issue.

**Comment by KoteshMCGit** [comment]
issue has been resolved and closing now.

**Comment by mikefactorial** [comment]
@tiyasasarkar This has been fixed in the latest release.
