### ISSUE TITLE
[Automation - BUG] AutomationCOE Power BI dashboard is not loading

### ISSUE THREAD

**Issue by christinatang-NAES** [microsoft/powercat-automation-kit#140]
### Describe the issue

We are trying to open the Power BI template inside AutomationKitInstall folder using Power BI desktop but after giving Main Environment URL (in the same format mentioned [organization].crm[N].dynamics.com), it is not getting loaded with the attached error.
![image](https://user-images.githubusercontent.com/107637236/214961815-e8181962-33c8-4a82-a2e3-05e5eed524e1.png)

### Expected Behavior

Dashboard should load and populate with correct data

### What component are you experiencing the issue with?

Power BI dashboard

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

Opening the Power BI template (file name: Automation.Kit.V1.0.20220914.pbit) inside AutomationKitInstall folder using Power BI Desktop.
Providing the Main Environment URL in the mentioned format ([organization].crm[N].dynamics.com).
The data was loading and after few mins got the attached error.
![image](https://user-images.githubusercontent.com/107637236/214961977-0a2bc05b-47f9-455f-93fa-87aed1ec881b.png)

**Comment by KoteshMCGit** [comment]
It seems, some network connection issue occurred in while fetching the details. 

Can you try once again. and share the exact error details or exact error screen shot.

**Comment by christinatang-NAES** [comment]
Hi Koteswara,

Thanks for the response. I'm getting the same error. Is this a permissions issue?
***@***.***

**Comment by KoteshMCGit** [comment]
can we connect once to verify the issue. Please ping me in kmarram@microsoft.com in Teams to connect

**Comment by christinatang-NAES** [comment]
My organization restricts connecting with external users. Could we set up a meeting instead? I am in Pacific Time Zone.
***@***.***

Thank you,

Christina Tang
Business Hyperautomation Lead

Direct: 425-270-6041 | Cell: 425-773-9739
***@***.***
***@***.***>
[Inline images 1]
NAES Corporation
1180 NW Maple St. Suite 200, Issaquah, WA 98027

www.naes.com<http://www.naes.com/>

**Comment by KoteshMCGit** [comment]
sure. you can schedule a meeting with me( kmarram@microsoft.com) in IST time (available after 6 PM IST).

**Comment by joshuadow** [comment]
This appears to be a column related issue in tables. I was also getting this issue until finally it gave me a real error message: "The column 'owningbusinessunitname' of the table wasn't found."

It is like this for every table is tries to query in the Automation.Kit.V1.0.20220914.pbit report.

**Comment by KoteshMCGit** [comment]
As per design the column should be available for flow session exception table. please find the below screen shot for more details

screen show owningbusinessunitname column.
![image](https://user-images.githubusercontent.com/107620140/216898885-bddce8fd-8c5e-4792-9eab-568ce6c7d1eb.png)


And also please do verify are there any columns failed to update data and showing as "Error". something like as below screen shot.

screenshot for completed data fields is not populated properly and showing as Error.
![image](https://user-images.githubusercontent.com/107620140/216899575-57a369d3-e371-4116-848f-bba99255f38a.png)

Please share your screen shots, to do further analysis.

**Comment by joshuadow** [comment]
The PowerBI report is looking for that column in almost every table related to the Automation Kit.

![image](https://user-images.githubusercontent.com/25085225/217002417-42e58be9-1a18-431f-a09b-f8d7b7a3e353.png)
![image](https://user-images.githubusercontent.com/25085225/217002529-d9d16342-4a3f-457f-acdf-45333cc4c79c.png)

and specifically the Flow Session Exception table, that column does not exist
![image](https://user-images.githubusercontent.com/25085225/217002907-2fcc39b9-0440-42bd-aa34-8f7e17d080de.png)

**Comment by joshuadow** [comment]
Can you please elaborate? I am not sure what you mean. Do you mean to publish the solution again and then trying to reload the report?

If so I am not sure that will work as that column does not exist in any of the DataVerse tables.

**Comment by KoteshMCGit** [comment]
According to below screenshot please do publish all customizations for Tables and choices from Main solution, which you are configured in dashboard.
![image](https://user-images.githubusercontent.com/107620140/217234626-f31344a3-0795-4994-95a5-eb2fae4b8c89.png)

After publishing of all customizations, try to connect dashboard. if still it is not loading, please connect with me kmarram@microsoft.com in Teams. i will help you to resolve the issue.
