### ISSUE TITLE
[Automation Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by tnblackford** [microsoft/powercat-automation-kit#141]
### What is your question?

What is the Business Owner tied to and how do I get users to show up as options?  It's not pulling any of our users, either in from our tenant or those added to the Automation CoE environment either with Security roles or Roles in the Automation Center.   I've even tried manually typing in a name, but that didn't work either.   It's supposed to be the person approving the bot in the workflow, but since I can't identify anyone, it keeps using the Fallback user.  

### What component is the question related to?

Automation Project

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

Automation Project

**Comment by KoteshMCGit** [comment]
As per our analysis, issue might with your office 365 users connection. Automation project app is using office 365 users connection to fetch users as business owner email. Please do verify once for respective permissions to read users from office 365 user connection for Automation Project app. 

Please find the below URL for more details on office 365 users connection.

https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/connections/connection-office365-users#add-a-connection

**Comment by pjrev** [comment]
@KoteshMCGit I'm experiencing the same issue. It seems the business owner field is just picking up the first 100 users.

**Comment by KoteshMCGit** [comment]
Recently we have observed a technical limitation (fetching 500 / 1000 emails) for usage of email collections in power apps. And working on that issue. and will update you once it is fixed.

**Comment by KoteshMCGit** [comment]
we have fixed the issue with using of office365users.searchuser function without any collections.

**Comment by pjrev** [comment]
@KoteshMCGit the fix will be pushed on the next release or is it available now on the latest Automation Kit?

**Comment by KoteshMCGit** [comment]
The fix will be available in this release "February 2023" we are planning to release in this week.

**Comment by tnblackford** [comment]
Great, thanks!

Tokin Blackford, LITP │ IS HQ Manager – Microsoft 365
Turner Construction Company │ Montrose, CO
mobile 970.275.5353 │ ***@***.******@***.***>
