### ISSUE TITLE
[Automation - BUG] DLP Impact Analysis for Desktop flow – not showing any desktop flow. 

### ISSUE THREAD

**Issue by tiyasasarkar** [microsoft/powercat-automation-kit#142]
### Describe the issue

In DLP Impact Analysis for PAD application we are not able to find any desktop flows. In the Satellite environment the desktop flows are present but it is not showing in this app (even without adding any filtering of Module and Actions).

### Expected Behavior

In DLP Impact Analysis for PAD application, the list of desktop flows present in that Satellite environment should be visible and we should able to filter the desktop flows based on Modules and Actions.

### What component are you experiencing the issue with?

Other

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

DLP Impact Analysis for PAD

**Comment by KoteshMCGit** [comment]
As per Design, App will show blank desktop flows list initially (without any filters). Later based on your filters, respective desktop flows will be shown.

Please do verify once for modules and corresponding actions should be populated on DLP Impact Analysis home page to filter desktop flows. if these two drop downs are blank, you have to import respective csv file and try again.

you can find the below URL for more details.
https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/dlp-impact-analysis

**Comment by KoteshMCGit** [comment]
I hope we have clarified your issue and closing the issue.

**Comment by tiyasasarkar** [comment]
As you said initially in DLP Impact Analysis app no desktop flows will be shown but after adding the filter (After choosing Modules and Actions) also no desktop flows showing. Please refer the screenshot below. 
Note: in 'Desktop Flows DLP Impact Profile' dataverse table, we are able to see desktop flow actions associated with the flow names but not reflecting in DLP Impact Analysis app.
<img width="950" alt="image" src="https://user-images.githubusercontent.com/123467998/216919900-1ad90a74-52ff-4bb3-ad38-5a2645b741d4.png">

**Comment by KoteshMCGit** [comment]
can we connect once to verify the issue as we are not reproduce. please connect kmarram@microsoft.com in teams to connect.

**Comment by KoteshMCGit** [comment]
As per our offline meeting with you, it is observed that browser zoom level is not correct and after setting zoom level, it is working fine and closing the issue now.

**Comment by mikefactorial** [comment]
@tiyasasarkar This has been fixed in the latest release.
