### ISSUE TITLE
[Automation - BUG] User without having  System Administrator/Automation Project Admin role is able to access Automation Center app

### ISSUE THREAD

**Issue by tiyasasarkar** [microsoft/powercat-automation-kit#143]
### Describe the issue

Users who does not have any admin roles (System Administrator/Automation Project Admin) , are able to access the Automation Center App even without sharing and also able to see all master data, automation project details in view mode.

### Expected Behavior

As per document, the Automation Center App is only used by CoE admins to configure master data, mapping automation projects to environments etc. but other users are also able to get access to this app. 

### What component are you experiencing the issue with?

Automation Center

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Automation Center

**Comment by KoteshMCGit** [comment]
For Basic user role, we dont get this app to access. 

Could you please let us know what roles are assigned other than System Administrator/Automation Project Admin roles.

**Comment by tiyasasarkar** [comment]
The users (other than System Administrator/ Automation Project Admin) who is having access to this app either have Automation Project Contributor or Automation Project Viewer Role along with Environment Maker role (without having Environment Maker role user was not able to access the environment only with Viewer/Contributor role).

**Comment by KoteshMCGit** [comment]
The roles Automation Project Admin, Automation Project Contributor, Automation Project Viewer Role is applicable to respective application access and usage but not to provide access to respective environment.

Please find the below URL, which helps you to understand more about provide access to respective environments.
https://learn.microsoft.com/en-us/power-platform/admin/add-users-to-environment
