### ISSUE TITLE
[Automation Kit - QUESTION] DLP configuration in Desktop Flow Action table.

### ISSUE THREAD

**Issue by tiyasasarkar** [microsoft/powercat-automation-kit#144]
### What is your question?

There is a dataverse table "Desktop Flow Action" present in both Main and Satellite solutions. As per document, we need to import the "autocoe_desktopflowactions.csv" file to this table. In this file "DLP Support" field for some actions are True/False. Could you please let us know how it is configuring that DLP support field and it is based on which DLP policy?
[autocoe_desktopflowactions.csv](https://github.com/microsoft/powercat-automation-kit/files/10556612/autocoe_desktopflowactions.csv)

### What component is the question related to?

Other

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Desktop Flow Action Table

**Comment by KoteshMCGit** [comment]
We have to import all desktopflowactions.csv file into Desktop Flow Action Table. These actions will be treated as single repository for DLP impact analysis Application. This application will helps you to find PAD flows based on different filters like DLP supported actions / Microsoft / 3rd part actions and etc.,

Please note that few actions are not supported to create Data loss prevention for PAD flows. so, we are flagging these actions which are supported or not. It is only for internal reference only.

please find the below URL for more details on DLP
https://learn.microsoft.com/en-us/power-automate/prevent-data-loss

**Comment by KoteshMCGit** [comment]
Please let me know if you have any questions on this. otherwise, we treat it is closed.
