### ISSUE TITLE
[Automation Kit - QUESTION] The CoE admins already have the System Administrator role to perform admin task then what is the use of Automation Project Admin role.

### ISSUE THREAD

**Issue by tiyasasarkar** [microsoft/powercat-automation-kit#146]
### What is your question?

In Automation Center App the CoE admins should only perform the admin tasks such as configuring master data, mapping automation projects to environments etc. We have explored that using System Administrator role admins can perform this, then what is the use of Automation Project Admin security role in Main Environment? because we can see if we assign this role to any other users they will get access to Automation Center app to perform admin tasks which is not expected.

### What component is the question related to?

Automation Center

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Automation Center

**Comment by KoteshMCGit** [comment]
The CoE admin Role will help you to configure all setup related activities for Automation kit.

The Automation Project Admin role will help you to manage all Automation projects (create /modify / configure satellite environment) and etc., you can create a specific user account with less privileges to perform only Automation projects without system admin role.

And also, please note that the user account should have roles like "Automation Project Admin" or "Automation Project Contributor" to create / modify Automation projects. without having of "Automation Project Admin" or "Automation Project Contributor", even though that user is having COE Admin role, he cannot create / modify automation projects through canvas app.

Please find the below URL for more details on automation kit setup and roles
 
https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/setup/main

**Comment by tiyasasarkar** [comment]
Thanks understood. But want to clarify that specifically for Automation Center App, CoE admins can perform the admin tasks (read and write permission on this app) by only having System Administrator Role? They don't need Automation Project Admin role also for this? because for us to perform admin task, separate users with System Admin and Automation Project Admin role is getting same privilege in Automation Center App.

**Comment by KoteshMCGit** [comment]
Yes your understanding is correct. As COE Admin will use Automation Center App to perform admin tasks and Environment mapping for projects. having of system admin is sufficient for CoE admins. Usually, CoE admins will not use Automation project App.

if CoE admins, want to use Automation project App to create project records, he needs Automation Project Admin role. hope you understand clearly. 

Please note that without using of Automation project App, COE admin can create project records with using Automation Center App.

**Comment by KoteshMCGit** [comment]
If you have any other questions on this, please let me know. otherwise, we will close this item.

**Comment by tiyasasarkar** [comment]
Yes we are good to close this issue.

**Comment by mikefactorial** [comment]
@tiyasasarkar This has been fixed in the latest release.
