### ISSUE TITLE
[Automation - BUG] Automation Solution is not getting metered and unable to sync data to Main Environment

### ISSUE THREAD

**Issue by tiyasasarkar** [microsoft/powercat-automation-kit#147]
### Describe the issue

We were evaluating Automation Kit and trying to create an end-to-end scenario to understand about it but we got stuck here. Using Automation Solution Manager app, after mapping the solution to the automation project as per document the "+" icon should switch to metered sign and the data sync back to the Main Environment.
![image](https://user-images.githubusercontent.com/123467998/216043272-243b17bb-3f4c-4b5e-bfb1-2ce5f4daca65.png)
But according to the following screenshot the metered sign is not showing. We have followed the naming convention of the cloud flow and also tried by disabling the naming convention.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/123467998/216043762-9a49678f-5cdf-46a0-b5c5-5f36e67411c1.png">

### What component are you experiencing the issue with?

Automation Solution Manager

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Automation Solution Manager

**Comment by crelke** [comment]
Hi @tiyasasarkar, try drilling down into the solution by clicking the solution name in the Name column. This should open a screen with your solution components that you can turn on the metering for. Let me know if this helps!

**Comment by tiyasasarkar** [comment]
We have drilled down into the solution and able to see its component (Desktop and Cloud flow) as per screenshot. After clicking on the checkbox 'Only metered cloud flow' its not showing anything. Though the solution is showing under Metered Solution, its artifacts are not getting metered. Please let us know here how we should turn on metering.

Note: We have followed the naming convention of the cloud flow and also tried by disabling flow naming convention but it didn't make any difference.
<img width="956" alt="image" src="https://user-images.githubusercontent.com/123467998/216927091-14e25dd7-f585-42d1-b943-257b74cb9b3f.png">

**Comment by KoteshMCGit** [comment]
You have to add metering for cloud flows also. Please find the below screen shot for your reference.

![image](https://user-images.githubusercontent.com/107620140/216996813-3bf8983f-027b-4545-9988-62782986192b.png)

once you have metered for cloud flows, your flow runs and sessions will be syncs with main environment. and later you can view on dashboard.
