### ISSUE TITLE
[Automation - BUG] E3 License Requirements Met But Unable to Launch Automation Project App

### ISSUE THREAD

**Issue by MCDAutomate** [microsoft/powercat-automation-kit#149]
### Describe the issue

Hi all,

I have an administrative account with an E3 license: 
![image](https://user-images.githubusercontent.com/124255872/216301736-ae27b64f-42b2-46e6-aa10-bdff913f6506.png)

As per the license requirements outlined in the [documentation](https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/setup/prerequisites#license-requirements): 
![image](https://user-images.githubusercontent.com/124255872/216301927-276a2350-24d6-492d-9493-f3289fcca351.png)

However, when I launce the Automation Project on my administrative account I am told I need to start a trial: 
![image](https://user-images.githubusercontent.com/124255872/216302396-04e94a85-c8e0-4ab5-b471-2ebb268246fb.png)

Can you confirm if a E3 licensing requirement is incorrect and another license is needed? 

### Expected Behavior

I expected an E3 license to be sufficient as per the documentation.

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Automation Project

### Steps To Reproduce

1. Have an account with an E3 license
2. Press Play on the Automation Project application

**Comment by Grant-Archibald-MS** [comment]
@MCDAutomate the E3/E5 licence is required for the Microsoft Office 365 connector.

To run the Power App you will require a Power App per user, Per app or Pay as you Go license.

**Comment by mikefactorial** [comment]
@MCDAutomate This has been fixed in the latest release.
