### ISSUE TITLE
[Automation Kit - Feature]: Environment Schedule View

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#150]
### Is your feature request related to a problem? Please describe.

As a Power Automate Desktop owner or Environment Administrator I would like the ability to view the scheduled Power Automate Desktop flows.

Aim to use the schedule to:
1. View scheduled flows
2. View the status of flows
3. View schedule work times across Machines / Machine Groups

### Describe the solution you'd like

Provide the ability to view daily, weekly and monthly scheduled Power Automate Desktop
View the start time and duration based on last run
The ability to filter on:
- Flow name
- Machine / Machine Group
- Status

**Comment by Grant-Archibald-MS** [comment]
Adding screenshots of work in progress user interface:

Day View
![image](https://user-images.githubusercontent.com/31553604/217310700-a2760a3e-6558-4d34-8316-08e67fe3e2aa.png)

Month View
![image](https://user-images.githubusercontent.com/31553604/217310860-dc41051c-2a57-4267-86a3-dde4ff3a16c1.png)

Schedule View:
![image](https://user-images.githubusercontent.com/31553604/217311188-833797a4-70f0-4390-b6e6-5b476a745d29.png)

**Comment by Grant-Archibald-MS** [comment]
Display the time in local browser locale converting schedule time from UTC. Consider future update that allows the user to select the timezone.

**Comment by biswapm** [comment]
Search, Filter with Status, Machine / Machine Group would be part of Phase 2.

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.

**Comment by suyash009** [comment]
Does this allow us to actually schedule and or is this just a view.

**Comment by Grant-Archibald-MS** [comment]
@suyash009 this release started with view of Power Automate Desktop flows that are called from a [recurring schedule](https://learn.microsoft.com/en-us/power-automate/run-scheduled-tasks)

In the next release we are investigating the following:
1. The ability to run a scheduled flow now from the calendar.
2. The ability to resubmit a failed flow run.

Another idea that could be considered is the ability to launch creation of a new flow so that can create the scheduled cloud flow.
