### ISSUE TITLE
[Automation - Question] In Desktop Flow Action table how the new actions will be added in future?

### ISSUE THREAD

**Issue by tiyasasarkar** [microsoft/powercat-automation-kit#152]
### Describe the issue

There is a dataverse table named 'Desktop Flow Action' where we need to import autocoe_desktopflowactions.csv file and it will be used in DLP Impact Analysis app to display the actions and also filter it with the actions used in desktop flows. But here we want to know, in future when new actions will be added to Desktop flows how it will get added to this table ? As we can't manually check every time that any new actions are available or not and add this to table.

### What component are you experiencing the issue with?

Other

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Desktop Flow Action table

**Comment by KoteshMCGit** [comment]
As per your comments it is not bug in the product. And this can be treated as question. 

Incase if we observe any new actions for desktop flows, We will update you through release notes /process. Accordingly, you can get updated the table desktop flow actions. You need not to check manually. Simply you can follow the Automation kit releases and understand the new features and bug fixes if we have any.

**Comment by mikefactorial** [comment]
@tiyasasarkar This has been fixed in the latest release.
