### ISSUE TITLE
[Automation Kit - QUESTION] Does the new Pipelines for Power Platform deploy PAD flows?

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#153]
### What is your question?

Does the [Pipelines for Power Pipeline](https://learn.microsoft.com/en-us/power-platform/alm/pipelines) allow deployment of Power Automate Desktop flows that are included in a Solution with Connection References to a Machine or Machine Group?

### What component is the question related to?

Other

**Comment by Grant-Archibald-MS** [comment]
Yes the public preview of the Pipelines for Power Pipelines will deploy a Power Automate Desktop flow that is called from a Power Automate Cloud flow that is included in a solution.

![image](https://user-images.githubusercontent.com/31553604/217685170-26e7fcca-bc2a-4199-98a5-e38216297104.png)

Some notes:
1. Ensure that the Power Automate Desktop flow is included in a solution
2. Use connection references for Machine / Machine group connections from the Cloud Flow to the Power Automate Desktop
3. The user publishing the solution needs system customizer role to export and [Import](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/import-update-export-solutions) the solution between environments

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.
