### ISSUE TITLE
[Automation - BUG] Automation Project Number is getting duplicate on top of sample data

### ISSUE THREAD

**Issue by KoteshMCGit** [microsoft/powercat-automation-kit#155]
### Describe the issue

Recently we have observed that project number is getting duplicate on Automation project application, after loading sample data from December 2022 Release.

because of this if you edit newly created project, it is taking old record (with same project number) and showing on UI to modify.

screen shot:
![image](https://user-images.githubusercontent.com/107620140/217836334-97a203b9-711c-4458-a075-f0f1be9ba3e4.png)

### Expected Behavior

After creating new project, Project record should show based on internal key field (may be Guid) and not based on project number. 

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Automation Project

### Steps To Reproduce

Install Main solution with load sample data option. 
1. Open the automation project app 
2. Create new project on top of sample data.
3. Provide all the necessary details
4. save the project.
5. you can observe the duplicate project number for newly created project.

**Comment by KoteshMCGit** [comment]
As per our analysis, after loading the sample data (Automation projects) from installer, internal seed value is not updating for respective table. As of now we don't have any option to increase seed value while importing. Usually, we don't get duplicate project number on empty database.

As per design, this project number is unique hence app is designed based on project number column.

In this case, we have modified the Automation project application by taking internal key field like GUID of Automation project for Modifying / Submitting from App.

**Comment by KoteshMCGit** [comment]
Validated and working fine with using of internal key field i.e GUID is used to modify / submit / view project details.

**Comment by mikefactorial** [comment]
@KoteshMCGit This has been fixed in the latest release.
