### ISSUE TITLE
[Automation Kit - Feature]: Scheduler - Run Flow

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#175]
### Is your feature request related to a problem? Please describe.

Extend #150 to provide the ability to run a scheduled flow now

### Describe the solution you'd like

Provide a context menu of action command that allows the selected flow to be run now

**Comment by suyash009** [comment]
Can you share some roadmap for the feature? Some details on what scenarios would this cover.

**Comment by Grant-Archibald-MS** [comment]
@suyash009 the current scope will be to enhance the February release to provide the ability to run the Power Automate Desktop flow using the existing [Power Automate Desktop Public APIs](https://learn.microsoft.com/en-us/power-automate/developer/desktop-flow-public-apis).

I future releases we will look at options to run the parent scheduled Cloud flow via the Power App.

**Comment by suyash009** [comment]
Do we have an options to run the parent scheduled Cloud flow? Is it planned for next release.?

**Comment by Grant-Archibald-MS** [comment]
@suyash009 I have created #202 so that you can track our plans and roadmap for the ability to run the parent cloud flow

**Comment by suyash009** [comment]
I have update my kit. But I cant see the Scheduler app. In which environment do I need to check? Is it a separate app.?

**Comment by suyash009** [comment]
@Grant-Archibald-MS How is this feature #175 different from #150 ?
