### ISSUE TITLE
[Automation Kit - Feature]: Scheduler Filter

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#177]
### Is your feature request related to a problem? Please describe.

Extend #150 by providing the ability to filter calendar items

### Describe the solution you'd like

Provide the ability to filter by the following:
- Flow name
- Flow Status (Success, Failed, Scheduled)
- Machine / Machine Group

**Comment by biswapm** [comment]
In the current release, a new filtering option has been added that allows users to filter by machine group or machine name. In the upcoming April release, additional filters will be added, including the ability to filter by status and flow name.
