### ISSUE TITLE
[Automation Kit - QUESTION] DLPs for Desktop flow actions in default environment

### ISSUE THREAD

**Issue by suyash009** [microsoft/powercat-automation-kit#180]
### What is your question?

Can we set setup DLPs for Desktop flow actions in Personal Productivity environment? Or just say can we setup satellite kit in Default or Personal productivity environment

### What component is the question related to?

Other

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

DLP App in Default (Personal Productivity) environment

**Comment by KoteshMCGit** [comment]
in general, we don't recommend you to install Automation Kit on default environment. if you would like to use DLPs for desktop, you can install satellite solution and try to access respective canvas app for DLP for PAD flows.

**Comment by mikefactorial** [comment]
@suyash009 This has been fixed in the latest release.

**Comment by suyash009** [comment]
@mikefactorial can you share what exactly is the fix.? Can I still use it for default environment
