### ISSUE TITLE
[Automation Kit - Feature]: Support Power Automate Desktop v1 and v2 definition

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#181]
### Is your feature request related to a problem? Please describe.

With the [announcement](https://powerautomate.microsoft.com/en-us/blog/power-automate-desktop-flows-in-dataverse-updates/) of the new v2 storage schema with the February 2023 (v.2.29) release if enable the [enable the v.2 storage schema through the feature toggle](https://aka.ms/v2schema) support flow that are saved with v2 format

### Describe the solution you'd like

Have the Automation Kit support Power Automate Desktop solutions saved in both v.1 and v.2 formats

**Comment by KoteshMCGit** [comment]
Analysis and development completed by modifying the existing plugin AutoCoE.Extensibility.

we have modified the code like below
![image](https://user-images.githubusercontent.com/107620140/223136509-253d4720-23f7-473b-a63c-9d55c5aebf4a.png)

Now our plugin will support for both old and v2 schema. if plugin is not found v2 schema, will work like old schema.

**Comment by KoteshMCGit** [comment]
Please find the below url for V2 schema impact analysis document

https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!eOCjEXTEWUq7m4FLzVGlEXMRbiamsOlOtQL9a6OTOdawvNF4XKv5RIm01x7B2Uji&item=01M2SGZVCSMGF6IV3HR5G2WLIO7WDEA2ND&file=https:%2F%2Fmicrosoft-my.sharepoint.com%2Fpersonal%2Fashwinrajuk_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint.com%2Fpersonal%2Fashwinrajuk_microsoft_com

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.
