### ISSUE TITLE
[Automation - BUG] DLP Profile - existing DLP profile records are getting deleted in specific scenario.

### ISSUE THREAD

**Issue by KoteshMCGit** [microsoft/powercat-automation-kit#187]
### Describe the issue

It is observed that existing DLP profile records are getting deleted, when a particular action occurrence count is changed ( increased / decreased) and saved desktop flow.

Example: 
Consider you are having Displaymessagebox action is one time in entire flow script along with other actions. If you add one more action with same Displaymessagebox action and saved. you can observe old actions will be deleted and only Displaymessagebox action will be with 2 occurrence count.

### Expected Behavior

Existing actions should not delete and only occurrence count needs to be updated in this scenario.

### What component are you experiencing the issue with?

Other

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

AutoCOE Plugin in satellite solution. 

### Steps To Reproduce

1. Create one desktop flow with below actions.
 Displaymessagebox 
LaunchExcel
Close Excel
2. Save the Desktop flow
3. you can observe 3 actions / selector records in Desktop Flow DLP Impact Profile table
4.  Now modify the same flow with below actions
5. Add one more Displaymessagebox action and save the flow.
6.you can observe 2 actions (launch excel and close excel actions) are removed and only 1 action / selector will be displayed with occurrence count =2

### Anything else?

No.

**Comment by KoteshMCGit** [comment]
we have fixed the issue in respective plugin and testing is in progress.

**Comment by mikefactorial** [comment]
@KoteshMCGit This has been fixed in the latest release.
