### ISSUE TITLE
[Automation - BUG] DLP Profiles - DLP Profile records are not deleted as per desktop flow script

### ISSUE THREAD

**Issue by KoteshMCGit** [microsoft/powercat-automation-kit#188]
### Describe the issue

It is observed that the DLP Profile records are not deleting, when PAD flow has modified of removing few actions.

Example:

Consider you are having a PAD flow with launchExcel, closeExcel and Displaymessagebox actions. Now you have removed the launchExcel and CloseExcel Actions. Now your PAD flow has only 1 action of Displaymessagebox action. but in respective table, you will be shown all 3 actions.

### Expected Behavior

In this scenario, Desktop Flow DLP Impact Profile table should contain only 1 record with Displaymessagebox. 

All deleted actions should be deleted in table and the same should be sync with main solution. 

### What component are you experiencing the issue with?

Other

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

AutoCoE.Extensibility plugin in satellite solution

### Steps To Reproduce

1. Create one PAD flow with below Actions
   LaunchExcel , Close Excel and DisplayMessageBox
2. you can observe 3 actions in Desktop Flow DLP Impact Profile table
3. Now Remove LaunchExcel and Close Excel actions and save the PAD flow.
4. you can observe all 3 records in respective Desktop Flow DLP Impact Profile table.

### Anything else?

No.

**Comment by KoteshMCGit** [comment]
Observed issue in plugin code and fixed. And also created a new cloud flow 'Sync Deleted selector from DLP Profile' to sync to main solution for deleted actions.

**Comment by mikefactorial** [comment]
@KoteshMCGit This has been fixed in the latest release.
