### ISSUE TITLE
[Automation Kit - QUESTION] Actual Savings in ROI financial dashboard shows negative values 

### ISSUE THREAD

**Issue by maheshnav** [microsoft/powercat-automation-kit#189]
### What is your question?

I see actual saving in negative. Is that expected behavior? 

![image](https://user-images.githubusercontent.com/21198978/223483766-4864d6bd-a7d1-499b-a9dc-8ecb083bc80f.png)

### What component is the question related to?

None

### What solution version are you using?

Feb 2023

### What app or flow are you having the issue with?

Power BI Dashboard - ROI financials

**Comment by KoteshMCGit** [comment]
usually it wont be negative values. Please do verify below items on power BI Dashboard

1. Ensure all the tables are populated from main environment to PB Dashboard. 
2. Have you observed any issues (like date time conversion / blank values) while refreshing the PB dashboard?
3. Have you configured Automation projects with respective manual processes time in mins column.

After verification of above items, please re-configure PB dashboard and refresh the dashboard. if you still observe the negative values, please connect with me (kmarram@microsoft.com) in Teams in IST time.

**Comment by maheshnav** [comment]
Thank you for your suggestions.  Fixed failing flows and issue seems to be fixed now and seen positive values.
