### ISSUE TITLE
[Automation - BUG] Metering not working

### ISSUE THREAD

**Issue by nasilvae** [microsoft/powercat-automation-kit#204]
### Describe the issue

Metering Functionality not working. 

![image](https://user-images.githubusercontent.com/95443860/225620429-2fb77338-9bea-4fd7-b283-fc20d6c8a212.png)
![image](https://user-images.githubusercontent.com/95443860/225620703-0572da1a-4a03-4e1b-a88f-9fbb96096b96.png)

![image](https://user-images.githubusercontent.com/95443860/225620999-d74a860b-aa8e-48e3-b871-06a1449a980c.png)
![image](https://user-images.githubusercontent.com/95443860/225621281-36e1abda-eb6b-415d-9c75-64117c2136c8.png)

Verified that account has admin permissions. All cloud flows are running as expected. 

### Expected Behavior

Metering should work. 

### What component are you experiencing the issue with?

Automation Solution Manager

### What solution version are you using?

1.0.20221217.1

### What app or flow are you having the issue with?

Automation Kit Application

### Steps To Reproduce

Started Metering Function. 
Nothing gets metered.

**Comment by RoboCreator85** [comment]
I'm having the same issue after completing the initial install/configuration. Please see my open issue for more details. 
https://github.com/microsoft/powercat-automation-kit/issues/201

**Comment by nasilvae** [comment]
Hi Team, 

We noticed that the Sync Flow Sessions Trace (Flow Session Trigger) flow is failing with the following error. 
![image](https://user-images.githubusercontent.com/95443860/228556092-c55fd0ac-473d-489a-ad17-ce94dcfe3028.png)
![image](https://user-images.githubusercontent.com/95443860/228556278-d6e9f17a-4445-4aa3-8fc0-5131dd918d6b.png)

We are also user an Application User as the owner to the desktop cloud flows which is not being found on the flow step.

**Comment by nasilvae** [comment]
> As per screen shot, it is issue with connection. can you please verify and ensure /re-create proper connections.
> 
> Please find the below screen shot for your reference for cloud flow "Sync Flow Session Trace (Flow Session Trigger)" ![image](https://user-images.githubusercontent.com/107620140/229501485-0e83dc18-32b4-4494-87a9-3b5c5bdc815a.png)

this has not fixed the issue. Do we have additional recommendations?

**Comment by KoteshMCGit** [comment]
As per our Analysis notes, we have to give a valid system user id (from system user table from Dataverse) to environment variable 'Flow Session Trace Record Owner Id'. This user id will be used to update in respective table Autocoe_flow session traces. 
As per your screen shot, the user id is not available in respective satellite environment. Hence it is giving error.

Please verify once for user id to given the environment variable 'Flow Session Trace Record Owner Id' and update correct user id from system user table in respective satellite environment.
