### ISSUE TITLE
[Automation - BUG] No schedules on scheduler app

### ISSUE THREAD

**Issue by suyash009** [microsoft/powercat-automation-kit#208]
### Describe the issue

I have created scheduled cloud flows that invoke  desktop flows. But even after running them their schedule is not shown on the scheduled app. 
I also added the cloud flow, desktop flow and the connection reference to a solution and triggered them. But still I cannot see the schedules on the app

![image](https://user-images.githubusercontent.com/11213587/226122545-63995033-b403-4ff2-b8a7-aa84ec0c9985.png)

![image](https://user-images.githubusercontent.com/11213587/226122560-fb3360fa-53b0-49f1-a231-e0d98f3f3971.png)

### Expected Behavior

After the scheduled cloud flows are created to trigger desktop flows. They should be visible on the scheduler app.

### What component are you experiencing the issue with?

Other

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

Flow Scheduler App

**Comment by suyash009** [comment]
@KoteshMCGit Could you give me a hand on the issue?

**Comment by suaysh009** [comment]
Only flows that are part of a solution are shown. Is this an expected behavior

**Comment by biswapm** [comment]
> Only flows that are part of a solution are shown. Is this an expected behavior

Yes, Flows are part of solution stores in Dataverse and will be only show on the scheduler. However, we are working towards pulling non-solution flows to be displayed in scheduler. For more info please refer here,  https://microsoft.github.io/powercat-automation-kit/features/scheduler/#cloud-flows
