### ISSUE TITLE
[Automation - BUG] Error occurred while reading secret: Service request failed from cloud flow "Get Dataverse Bearer Token (Azure KeyVault Env)"

### ISSUE THREAD

**Issue by rajendrakumar2021** [microsoft/powercat-automation-kit#211]
### Describe the issue

Getting  below error in Automation CoE Satellite env's "Get Dataverse Bearer Token (Azure KeyVault Env)"  cloud flow of Automation CoE Satellite solution.

the account has admin access on the Azure Key vault and App registration.

=========================
Error occured while reading secret: Service request failed.
Status: 403 (Forbidden)

Content:
{"error":{"code":"Forbidden","message":"The user, group or application 'appid=00000007-0000-0000-c000-000000000000;oid=aa577303-1cc7-42c2-a7a8-99953fde5258;iss=https://sts.windows.net/ed2d4aa0-93e5-4b9f-aec4-eeca68ce073d/' does not have secrets get permission on key vault 'KV-PA-Train;location=eastus'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287","innererror":{"code":"AccessDenied"}}}

Headers:
Pragma: no-cache
x-ms-keyvault-region: eastus
x-ms-client-request-id: 45a39178-ec3a-46b3-bffa-6be16ecf2f9c
x-ms-request-id: 7ed84a89-de4d-45f1-a6c2-75faf63dbfcb
x-ms-keyvault-service-version: 1.9.736.1
x-ms-keyvault-network-info: conn_type=Ipv4;addr=20.49.111.109;act_addr_fam=InterNetwork;
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
Content-Length: 433
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Mon, 20 Mar 2023 21:20:15 GMT
Expires: -1

### Expected Behavior

it should ideally run the cloud flow in getting the dataverse data.

### What component are you experiencing the issue with?

Cloud flows

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

Get Dataverse Bearer Token (Azure KeyVault Env)

### Steps To Reproduce

1) Training environment
2) Automation CoE Satellite solution
3) Get Dataverse Bearer Token (Azure KeyVault Env) cloud flow.

<img width="957" alt="CoE Error" src="https://user-images.githubusercontent.com/88549823/227298684-95241d1d-2a5b-4f14-b590-b33ed06efa13.png">

**Comment by KoteshMCGit** [comment]
As per above documentation, I hope it is fixed by setting proper permissions to read secret values. 

Currently we are working on another user story / feature https://github.com/microsoft/powercat-automation-kit/issues/84 is that removal of azure key Vault dependency for satellite solutions. And we are targeting to release in the month of April 2023. 

We suggest you can upgrade with April 2023 release to eliminate azure keyvault dependency.
