### ISSUE TITLE
[Automation Kit - QUESTION] Can Projects Submitted or Approved be deleted?

### ISSUE THREAD

**Issue by tnblackford** [microsoft/powercat-automation-kit#215]
### What is your question?

Is there any way to delete submitted/approved projects?  We added some test projects into the app so we could understand how it all worked and now we have some test projects we'd like to get rid of so they're not cluttering up our actual projects.  It won't let you delete from the Automation Center/Automation Projects list.  

### What component is the question related to?

Automation Center

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

Automation Center/Automation Project

**Comment by KoteshMCGit** [comment]
As per design, we cannot delete Automation projects, which are Submitted or Approved.
