### ISSUE TITLE
[Automation Kit - QUESTION] 'Sync_New_Desktop_Flow_Impact_Profile_to_CoE_Main' failed errro on one of satellite env.

### ISSUE THREAD

**Issue by maheshnav** [microsoft/powercat-automation-kit#234]
### What is your question?

'Sync_New_Desktop_Flow_Impact_Profile_to_CoE_Main' failed errro on one of satellite env.

Flow Name: Sync Desktop Flow DLP Profile

Error detail-  
A record that has the attribute values Selector Id, Desktop Flow Id already exists. The entity key DesktopFlowKey requires that this set of attributes contains unique values. Select unique values and try again.

Any solution to this problem?

### What component is the question related to?

Cloud flows

**Comment by maheshnav** [comment]
Not able to re-produce issue but seems to fixed. Not seen any new errors

**Comment by Grant-Archibald-MS** [comment]
Closing as cannot be reproduced
