### ISSUE TITLE
[Automation - BUG] Not able to open cloudflows console to add for metering in ASM

### ISSUE THREAD

**Issue by maheshnav** [microsoft/powercat-automation-kit#237]
### Describe the issue

Not able to open cloudflows console to add for metering in all Satellite environments > Auto Solution Manager console ....

GetDataverseSolutionArtifacts.Run failed: { "error": { "code": 502, "source": "unitedstates-002.azure-apim.net", "clientRequestId": "33c162d3-7305-44a2-aac5-ebf93b94e700", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08585197119473183820491215182CU55'." } } } }

![image](https://user-images.githubusercontent.com/21198978/233025724-1f25ce0a-382f-4cac-936e-bf01c80113f8.png)

### Expected Behavior

It should open solution and display exiting cloud flows to add to metering them.

### What component are you experiencing the issue with?

Automation Solution Manager

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

All Satellite environment >ASM console

### Steps To Reproduce

1. Open ASM console for respective Satellite Environment 
2. Open existing metered solution or add new solution for metering.
3. it will open solution to see cloud flow and add to metering, however no flows visible and throws above error

**Comment by maheshnav** [comment]
Getting below error while running "GetDataverseSolutionArtifacts" cloud flow from all satellite environments...

We couldn't able to retrive solution components from table 'msdyn_solutioncomponentsummary'. Original exception message:Entity 'systemuser' With Id = e4fcf585-9fa7-ed11-aad1-00224805c3e1 Does Not Exist

**Comment by KoteshMCGit** [comment]
As per above error or logs, no user id exists with e4fcf585-9fa7-ed11-aad1-00224805c3e1 in stystemuser Dataverse.

Could you please verify the system user id of application user in satellite environment and update to environment variable autocoe_SolutionManagerArtifactsReadUserID. And then please turn off and turn on for cloud flow "GetDataverseSolutionArtifacts" to read updated userid from environment variables before try to meter the solution.

**Comment by KoteshMCGit** [comment]
Please find the below steps to find application user id and update to environment variable

Screen shot of system user table in power apps dataverse

power apps>> Tables>> search with "user"
![image](https://user-images.githubusercontent.com/107620140/234342754-507957ab-c248-4ca7-b926-97718fe5dd87.png)


screen shot of system user table data and find your application user in this table
![image](https://user-images.githubusercontent.com/107620140/234343918-4f3df47a-4243-48c4-91f9-6808bc5bbc63.png)

copy system user Id and update for satellite solution Environmen variable (Solution Manager Artifacts Read User Id)  like below screen shot
![image](https://user-images.githubusercontent.com/107620140/234344780-9d2fcf92-d76a-4bf3-b6ca-e1717d939a64.png)


After that please turn off and turn on for cloud flow "GetDataverseSolutionArtifacts" to read updated user id from environment variables before try to meter the solution.

**Comment by maheshnav** [comment]
Thanks for the suggestions. It worked for me. Now back to normal once again.

**Comment by Sunildeokule2024** [comment]
> As per your above comment, Now it is working fine so we are closing the issue.

Hello 
I am also facing same issue can you please help me to resolve it
