### ISSUE TITLE
[Automation Kit - Feature]: Add new URL fields to add links to external assets such as process maps and documents 

### ISSUE THREAD

**Issue by jpad5** [microsoft/powercat-automation-kit#239]
### Describe the solution you'd like

Should be able to add multiple links to external assets when submitting an Automation Project

**Comment by KoteshMCGit** [comment]
We have implemented a new field 'Project Information URL' in Automation project creation screen.

we have created a new field 'Project Information URL' Field in respective data verse table with 500 chars max length. This is optional field and End user can give URL up-to 500 chars. 

End user can click on this new link and navigate to respective URL to know more about project

screen shot of newly created column 'Project Information URL' in Dataverse table 'Autocoe_AutomationProject'
![image](https://user-images.githubusercontent.com/107620140/236213749-6e8fb504-349a-4ced-9728-1d0967bfeb9a.png)


New Automation Project creation screen shot with new field 'Project Information URL'
![image](https://user-images.githubusercontent.com/107620140/236212512-e3fea621-832d-4a34-a939-38a0ef0662de.png)

Automation Project modification screenshot with new field 'Project Information URL'

![image](https://user-images.githubusercontent.com/107620140/236212708-8b1c5ea8-7bb7-46a0-ace7-50e89f0f643d.png)

View Project Details screenshot new field 'Project Information URL'
![image](https://user-images.githubusercontent.com/107620140/236212910-85220496-f829-403d-aeb9-09d3dcc1de34.png)
