### ISSUE TITLE
[Automation - BUG] POWER BI FAILS TO LOAD

### ISSUE THREAD

**Issue by nbetters** [microsoft/powercat-automation-kit#240]
### Describe the issue

Power BI fails to load (from the most recent release) stating there is an invalid server name (which I copied directly from the browser.
I have tried both with and without the HTTPS and it fails either way

### What component are you experiencing the issue with?

Power BI dashboard

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

AutomationKit Power BI

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/55587135/234927019-7b12175b-f4ba-4ed9-a0de-35e26b9f92ed.png)

This is with the HTTPS
![image](https://user-images.githubusercontent.com/55587135/234927969-4f3722e6-eae8-460a-9108-81f18e121036.png)

Removing the https results in an OLEDB error
![image](https://user-images.githubusercontent.com/55587135/234928359-3422c15f-a611-4b67-8d25-dd96c62bb771.png)

And I am onsite at our office so connectivity is not an issue. (350MBS connection speed)
![image](https://user-images.githubusercontent.com/55587135/234928987-75e861eb-ffb9-414f-abf5-890f1602e72b.png)

**Comment by KoteshMCGit** [comment]
Analysis is in progress.

**Comment by nbetters** [comment]
Where is the source file for the updated PBI, I cannot see it in the assets for the latest release?
