### ISSUE TITLE
[Automation - BUG] ASM not opening as expected

### ISSUE THREAD

**Issue by maheshnav** [microsoft/powercat-automation-kit#278]
### Describe the issue

ASM console not working or opening as expected. Getting below error..

![image](https://github.com/microsoft/powercat-automation-kit/assets/21198978/84bf13d7-c0a4-411a-98e7-88fe24b71801)

E5, RPA licenses as well per flow lice to CoE main environment assigned.

Not able to open Automation Console, Automation Project, DLP in Main Environment and Auto Solution Manager in Satellite as well. Getting same error.

### What component are you experiencing the issue with?

Automation Solution Manager

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

ASM console

**Comment by KoteshMCGit** [comment]
Analysis is in progress. As per error message, you dont have sufficient Power apps plan / licenses.

**Comment by maheshnav** [comment]
Per Analysis, It points to License but I have all needed licenses- Office E5, RPA attended and per flow to the coe main environment.

**Comment by maheshnav** [comment]
This issue is resolved after assigning power app plan 2 trail free licenses. However, I am not able to understand why it was not allowing before when I had E5 and RPA valid licenses.?
