### ISSUE TITLE
[Automation - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by mabaugh83** [microsoft/powercat-automation-kit#309]
### Describe the issue

Trying to import the csv file and get Unexpected error (Session ID: e09c013c-07e6-4d22-b6c0-6e5c7a165276, Region: gov)

### Expected Behavior

would expect import to work

### What component are you experiencing the issue with?

Other

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Core

### Steps To Reproduce

1. click on Descktop FLow Action in solution
2. Click import 
3. Select csv file 
4.get error Unexpected error (Session ID: e09c013c-07e6-4d22-b6c0-6e5c7a165276, Region: gov)

### Anything else?

have had this work in commercial but first time in GCC

**Comment by KoteshMCGit** [comment]
Can you please try to import once. we are in thinking that at the movement some internal issue might come and failed.

You can connect me kmarram@microsoft.com in Teams to verify and fix the issue.

**Comment by RajeevPentyala** [comment]
Closing this issue due to recent inactivity. Please feel free to reach out if you need further assistance. FYI @mabaugh83
