### ISSUE TITLE
[Automation - BUG] Automation Solution Manager - No data for solution

### ISSUE THREAD

**Issue by G1982C** [microsoft/powercat-automation-kit#311]
### Describe the issue

When opening the Solution Manager we have selected the solution created in the satellite environment, applied the Automation Project and then tried to open the solution and get the error below

<img width="1128" alt="Atuomation Pojrect" src="https://github.com/microsoft/powercat-automation-kit/assets/117096415/bdaf2779-b3f2-49b5-81fe-467a8d6b51c7">

As a result we are unable to see the cloud flows to enable the metering. 

Any ideas on what might be causing this issue? Thanks

### Expected Behavior

Able to open the solution in the Solution Manager and to see the cloud flows created as part of that solution

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Solution Manager

**Comment by bilodeauju** [comment]
Hello, this looks like it could be the same issue I reported here https://github.com/microsoft/powercat-automation-kit/issues/310
I included a workaround in case that helps.

**Comment by G1982C** [comment]
That is amazing, thank you @bilodeauju. Your instructions were spot on. I updated the variable in the default solution and it is now working as expected. 

To be honest, I was about to give up with using the Automation Kit as there doesn't appear to be much in way of support provided. Now that has been resolved, I may just try to perservere a little longer with trying out the kit.

**Comment by RajeevPentyala** [comment]
Closing this issue due to recent inactivity. Please feel free to reach out if you need further assistance. FYI @G1982C
