### ISSUE TITLE
[Automation - BUG] Automation project app - "Office365Users.UserProfile failed" error when selecting business owner

### ISSUE THREAD

**Issue by bilodeauju** [microsoft/powercat-automation-kit#313]
### Describe the issue

My organization started testing end-to-end scenario (https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/test-end-to-end) to see if we want to adopt the Automation kit. When using the Automation Project App and selecting a business owner, we get an error "Office365Users.UserProfile failed", "No user found with the specified id".

![image](https://github.com/microsoft/powercat-automation-kit/assets/81716086/599d7fec-a865-4e99-8ddb-0096eb57a808)

Upon further testing, I noticed I can select a business owner only when the account's primary email addresses matches with the user principal name (UPN). We are a very large organization and all of our employees are setup to have a different primary email address than their UPN. Only very few admin accounts or service accounts have matching email and UPN.

### Expected Behavior

We would expect the Automation Project app to allow selecting a business owner regardless of whether the account's primary email address matches with the UPN. Otherwise we would be stuck always using the fallback approver. 

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Automation Project app

### Steps To Reproduce

1. Sign in to Power Apps and then change to the main environment.
2. Launch the [Automation Project](https://github.com/microsoft/automation-coe/wiki/How-to-use-Automation-Project) app. 
3. Create a new automation project request by selecting "Add project"
4. Fill in the details and select a business owner that has an account with a different email address and UPN.

**Comment by KoteshMCGit** [comment]
Analysis is in progress.

**Comment by Grant-Archibald-MS** [comment]
To review if Basic User is required in addition to the roles described in [Assign Security Roles](https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/setup/main#assign-security-roles) of the Setup the main environment documentation.

If confirmed that **Basic User** is required update setup documentation to revise that this role is required.

**Comment by Grant-Archibald-MS** [comment]
@bilodeauju to update on review statis for this issue and provide feedback if documentation needs to be updated to remove error with additional role assignment.

**Comment by bilodeauju** [comment]
@Grant-Archibald-MS To clarify, the error "Office365Users.UserProfile failed" when selecting a business owner persists even with the "Basic User Role" added. We are unable to select a business owner and always stuck using the fallback approver every time we create a new project. 

Adding the "basic user role" resolved the other issue I submitted: https://github.com/microsoft/powercat-automation-kit/issues/312#issuecomment-1681246551

**Comment by RajeevPentyala** [comment]
@bilodeauju Fix has been made and will be available in September release.
