### ISSUE TITLE
[Automation Kit - Feature]: Satellite Dataverse plugin build from source code

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#33]
### Is your feature request related to a problem? Please describe.

Current process includes the compiled dataverse plugin inside the source code repository for the Automation Kit. This distribution approach has the current areas that need the solution extended to provide:
- Transparency of the code inside the plugin
- Auditability of the build process with code compiled in hosted build agent
- Limits integration with CI/CD solutions
- Ongoing process that can be executed to execute as .Net Frameword changes and fixes are applied 

### Describe the solution you'd like

Provide the ability for the Azure DevOps build pipeline can compile and include the binary plugin as part of the build and deployment pipeline

### Additional context?

The Automation Kit currently uses the ALM Accelerator to build and deploy releases of the Automation Kit to GitHub. The ability to support build plugins as part of the ALM Accelerator has been considered. Based on feedback and prioritization collaborate with ALM Accelerator team to add ability to support building Dataverse plugins as part of the deployment process.

As the ability to build plugins is supported as part of the ALM Accelerator upgrade the Automation Kit CI/CD process to take advantage of this feature to address the problem points raised.

**Comment by KoteshMCGit** [comment]
Respective azure dev ops pipeline has been modified and now plugin code is compiling from git hub repository.
