### ISSUE TITLE
[Automation - BUG] Traces not showing up for Cloud Flows without RPA

### ISSUE THREAD

**Issue by FelipeLujan** [microsoft/powercat-automation-kit#335]
### Describe the issue

Hi,

In multiple Satellite environments, I marked Cloud flows as metered artifacts. Some of those flows are exclusively Cloud flows, and some reference desktop flows.

When I launch the Automation Center model-driven app in the main environment, under Flow Sessions, I only see records of type Cloud Flow with RPA.

* All my flows are included in solutions.

### Expected Behavior

* The Flow Sessions tab in the Automation Center App shows traces of **both** Cloud Flows and Cloud Flows With RPA from satellite environments.
* Cloud Flow sessions are counted in ROI estimations
* In the Automation Kit PBI report, ROI tab, the projects filter shows projects that contain both cloud flows and cloud flows with RPA.

### What component are you experiencing the issue with?

Cloud flows

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Automation Center

### Steps To Reproduce

1. install main solution in main environment
2. install satellite solution in multiple environments PROD satellite environments.
3. Create and approve the project in the automation project power app, main environment.
4. in the Satellite environment, Automation Solution Manager app, click the + icon for the solution containing the flows I want to measure, link the solution to a project.
5. The power app will display the flows in the solution selected in step 4.  Click Disable Flow naming convention
6. Select the flow you want to measure, click "+ meter cloud flow", click yes.

**Comment by KoteshMCGit** [comment]
As per design, Automation kit will not use cloud flows without RPA for ROI calculation. As it is a technical limitation is that we don’t get Flow Session information for running of cloud flows without RPA / PAD flow attached. 
It is a general practice is that every cloud flow will be attached a desktop / PAD flow to complete Automation process.
We request you to please configure / meter the cloud flows, which are attached PAD flows.

**Comment by KoteshMCGit** [comment]
As per design, Automation kit will not use cloud flows without RPA for ROI calculation. As it is a technical limitation is that we don’t get Flow Session information for running of cloud flows without RPA / PAD flow attached. 
It is a general practice is that every cloud flow will be attached a desktop / PAD flow to complete Automation process.
We request you to please configure / meter the cloud flows , which are attached PAD flows.

**Comment by RajeevPentyala** [comment]
Closing this issue due to recent inactivity. Please feel free to reach out if you need further assistance. FYI @FelipeLujan
