### ISSUE TITLE
[Automation - BUG] satellite solution import failed from latest aug releases 

### ISSUE THREAD

**Issue by maheshnav** [microsoft/powercat-automation-kit#336]
### Describe the issue

 satellite solution import failed from latest august month releases -  file name - "AutomationCoESatellite_1.0.20230616.1_managed.zip"

### Expected Behavior

Version is showing lower where as it should be higher to import with in satellite environment..

### What component are you experiencing the issue with?

Other

### What solution version are you using?

May-2023

### What app or flow are you having the issue with?

Satellite kit release aug month

### Steps To Reproduce

Failing to import satellite solution due to versioning issue as per image attached`

### Anything else?

![image](https://github.com/microsoft/powercat-automation-kit/assets/21198978/7c3a38e4-9c58-4505-9629-72de5a93136b)

**Comment by biswapm** [comment]
@maheshnav Please upgrade to the latest September month release and share your feedback with us.

**Comment by RajeevPentyala** [comment]
Closing this issue due to recent inactivity. FYI @maheshnav. Please feel free to reach out if you need further assistance.
