### ISSUE TITLE
[Automation - BUG] ROI Calculation does not consider Volume per Frequency 

### ISSUE THREAD

**Issue by ashVancouver** [microsoft/powercat-automation-kit#339]
### Describe the issue

Currently if a process run had multiple transactions, the ROI calculator takes into account only one transaction and does not account for the rest of the transactions.

Example 

Process Frequency : Monthly
Volume per Process run : 600
Per transaction time saved : 2 mins

**Monthly Savings Calculation** 
**Expected**
Time Saved : Frequency * Volume per process run * transaction time saved = 1* 600 * 2 = 1200 mins 

**Automation Kit calculates it incorrectly**
Time Saved :  Frequency * transaction time saved  = 2 mins 

The above calculation is in correct as the volume per process run is not accounted for and only the frequency is included.

### Expected Behavior

ROI calculation should include Volume per process frequency (currently it does not)

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Incorrect Calculation 

### Steps To Reproduce

Create a metered solution with multiple transactions per process run.

**Comment by KoteshMCGit** [comment]
As per our Analysis, and product design, the field 'Volume per process run' is used only for information purpose. we have never used in ROI calculation. 

For Estimated ROI calculation, we can change the logic. But whereas coming to Actual ROI calculation, Automation kit is not having any option to read / provide actual transactions process count in a particular BOT run.

As per my view, we have to modify both Estimated and Actual ROI calculation with using 'Volume per process run' field. I am thinking this is not issue but we have to categorize this is as enhancement. As you might be aware of that Currently ROI calculation is enhancing to support work queues. we have to incorporate this change also in ROI calculation change.

If you are agree/fine for my above analysis notes, we can change this issue from Bug to Enhancement and implement the same later.

**Comment by RajeevPentyala** [comment]
Closing this issue due to recent inactivity. FYI @ashVancouver . Please feel free to reach out if you need further assistance.
