### ISSUE TITLE
[Automation - BUG] Dataverse Solution Arftifact Type choice in satellite solution

### ISSUE THREAD

**Issue by FlowAltDelete** [microsoft/powercat-automation-kit#39]
### Describe the issue

Inside the satellite solution the choice "Solution Arftifact Type" is misspelled.
![image](https://user-images.githubusercontent.com/79325340/191125577-335da087-b099-4862-9ba9-775687fcd883.png)
 

### Expected Behavior

The name should be "Solution Artifact Type".

### What component are you experiencing the issue with?

Other

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Choices type called Solution Arftifact Type

**Comment by Grant-Archibald-MS** [comment]
Updated
![image](https://user-images.githubusercontent.com/31553604/199628497-8dd4dfe6-6bec-44f8-b1ef-5873b18710bd.png)
