### ISSUE TITLE
[Automation Kit - Feature]: Meter more than 1 cloud flow

### ISSUE THREAD

**Issue by FlowAltDelete** [microsoft/powercat-automation-kit#41]
### Is your feature request related to a problem? Please describe.

Right now you can only meter one cloud flow from the metered solution. If there are multiple child flows than this also makes it hard to configure for metering for ROI.

### Describe the solution you'd like

Be able to meter multiple flows in the metered solution.

### Additional context?

The current limitation is only only one flow within a solution can be metered. The request is to have the ability to meter multiple flows within a solution. The use case is that based on the condition, the flow that is triggered varies (i.e. there could be more than one parent flow in the solution)

Scenario : Consider a process which can be triggered by an email or by a file entry in a shared folder. Depending on the back office team that is responsible for a given day, the trigger could either be an email or a file entry in a shared folder. In this case, there are more than one parent flows in the solution. Our current metering implementation only allows one flow to be designated as the parent flow. This limitation will lead to incorrect ROI measurement for the above scenario.

**Comment by KoteshMCGit** [comment]
It is a duplicate issue with 130 and 130 issue has been fixed.
