### ISSUE TITLE
[Automation - BUG] Automation Console, configs not clickable

### ISSUE THREAD

**Issue by WouterF** [microsoft/powercat-automation-kit#44]
### Describe the issue

After defining a new console config, it is not clickable. The link is configured in the console config.
![image](https://user-images.githubusercontent.com/5990852/191957091-c2cc837b-897e-4f98-a033-e192096111bd.png)

### Expected Behavior

The console config should be clickable

### What component are you experiencing the issue with?

Other

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Automation Console Canvas App

### Steps To Reproduce

Define a "Console Configuration" item via the Automation Center model-driven app
Open the "Automation Console" app and try to click

**Comment by WouterF** [comment]
It looks like it is fixed. I had assigned the security role via a Dataverse team (O365 group) but it was not correctly assigned.
After assigning the security role directly to the user, the icons to click are visible.
Thanks for this nice solution. Looking forward to the next versions!
![image](https://user-images.githubusercontent.com/5990852/191968512-65df316b-5d0e-4418-a1a4-5eb84bc1d702.png)

**Comment by KoteshMCGit** [comment]
started looking into the issue and analysis is in-progress.

**Comment by mikefactorial** [comment]
@WouterF This has been fixed in the latest release.
