### ISSUE TITLE
[Automation - BUG] Flow Session Exception Alert Always States Flow was Disabled

### ISSUE THREAD

**Issue by ChadDyess-MS** [microsoft/powercat-automation-kit#45]
### Describe the issue

When you create a flow exception rule that sends an alert but does not disable the flow, the alert email you receive still states that the flow was disabled. This is because in the Flow Session Exception Sync flow, there is not a separate email action for sending alerts without the disabled flow language.

### Expected Behavior

When you create a flow exception rule that does not disable the flow but sends an alert, the alert email should not state that the flow has been disabled.

### What component are you experiencing the issue with?

Cloud flows

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Flow Session Exception Sync

### Steps To Reproduce

1. Create a flow session exception rule where "Send Alerts" = Yes and "Turn Off Cloud Flow" = No.
2. Set Consecutive Exception Count to 3.
3. Test running a flow that will fail 3 times.
4. Verify that the email alert says that the flow was disabled.

**Comment by KoteshMCGit** [comment]
Started analyzing the issue.

**Comment by mikefactorial** [comment]
@ChadDyess-MS This has been fixed in the latest release.
