### ISSUE TITLE
[Automation - BUG] Automation Project Viewer role cannot see any projects

### ISSUE THREAD

**Issue by ChadDyess-MS** [microsoft/powercat-automation-kit#49]
### Describe the issue

If a user with the Automation Project Viewer role opens the Automation Project app, the user will not see any projects, even if you click the refresh button.

### Expected Behavior

A user with the Automation Project Viewer role, but not Automation Project Contributor or Automation Project Admin role should be able to view all projects in the Automation Project App, but should have read-only access. 

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Automation Project

### Steps To Reproduce

1. Add a user to the Automation Project Viewer role, and make sure they do not have Automation Project Contributor or Automation Project Admin role.
2. Open the Automation Project app
3. User will not see any projects in the list

**Comment by KoteshMCGit** [comment]
started looking into the issue
