### ISSUE TITLE
[Automation - BUG] Automation Project Admin role does not see all projects in Automation Project app until clicking refresh icon

### ISSUE THREAD

**Issue by ChadDyess-MS** [microsoft/powercat-automation-kit#50]
### Describe the issue

When a user that has the Automation Project Admin role but not Automation Project Contributor or Automation Project Viewer role opens the Automation Project App, the project list is empty. The user must click the refresh icon beside the search box in order to see all projects.

### Expected Behavior

A user a with the Automation Project Admin role should be able to see all projects when they open the Automation Project app, without having to click the refresh icon.

### What component are you experiencing the issue with?

Automation Project

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Automation Project

### Steps To Reproduce

1. Add a user to the Automation Project Admin role, and make sure they do not have Automation Project Contributor or Automation Project Viewer role.
2. Open the Automation Project app
3. User will not see any projects in the list
4. Click refresh icon
5. User will see all projects in the list

**Comment by KoteshMCGit** [comment]
started looking into the issue
