### ISSUE TITLE
[Automation Kit - Feature]: Integrate Process Advisor into the Kit

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#65]
### Is your feature request related to a problem? Please describe.

Feedback 

> "[Process Advisor](https://learn.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-automate/process-advisor) seems very complimentary yet disconnected with the current release"

### Describe the solution you'd like

 Allow a process to be recorded with process advisor to be used in the automation kit to help with ROI calculations, selecting the process to automate and then ultimately monitor to visualize the actual vs expected gains

**Comment by Grant-Archibald-MS** [comment]
To support this approach the following is being considered:
1. Addition of a new Process Advisor link in the Automation Project so that a Project Contributor can add a hyperlink to the Process Advisor information
2. Read only view of the Process Advisor link by Automation Project Reviewer and Viewer
3. Hyperlink from the Power BI report to Process Advisor

Documentation on the http://aka.ms/ak4pp/starter site or learn site that describes how Process Advisor information can be used with the Automation Kit

Related backlog items will look at automated processes that could be used to prevent manual rekey of information between the two systems.

**Comment by Grant-Archibald-MS** [comment]
Possible visual. Include the link to process advisor and key fields from the Process Advisor Dashboard

![image](https://user-images.githubusercontent.com/31553604/202054726-5997f804-f8bb-4144-a782-f4db1f542efd.png)

Create a configurable profile that includes common fields so that user limits the amount of commonly entered fields. For example:
- Department
- Work Days Per Year
- Hours Per Day
- Hourly FTE Cost
- Corporate Goal(s)

**Comment by Grant-Archibald-MS** [comment]
Related explanation of area being explored as part of backlog area of the starter site https://microsoft.github.io/powercat-automation-kit/backlog/process-advisor-integration

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.
