### ISSUE TITLE
[Automation - BUG] Install not to work with September Creator Kit

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#74]
### Describe the issue

When install the https://github.com/microsoft/powercat-creator-kit/releases/tag/CreatorKit-September2022 release of creator kit needed to save and publish new version of applications to work with  September release

Options
1. Install the https://github.com/microsoft/powercat-creator-kit/releases/tag/CreatorKit-August2022 release
2. Upgrade solutions to September

Provide new release solution release that is compatible with September release

### Expected Behavior

Works with changing version of Creator Kit

### What component are you experiencing the issue with?

Other

### What solution version are you using?

October 2022

### What app or flow are you having the issue with?

Application

### Steps To Reproduce

1. Install September release of Automation Kit
2. Install September release of Creator Kit
3. Unable to see visuals without install August Release of Creator Kit or Save Application with September release of Creator Kit

**Comment by Ramakrishnan24689** [comment]
@KoteshMCGit , @Grant-Archibald-MS  Can you please confirm which visuals are impacted ? 
By visuals, I am assuming these are code components and not Power BI visuals.

**Comment by Grant-Archibald-MS** [comment]
Looking to reproduce the original issue and while testing with October release of Creator Kit version [1.0.20221004.2] and Automation Kit Main solution [1.0.20220913.3] and unable to reproduce the issue.

Closing the issue unless further reproduction steps available

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.
