### ISSUE TITLE
[Automation Kit - Feature]: Automated Deployment via pac cli

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#82]
### Is your feature request related to a problem? Please describe.

Simplify the install process by allowing automated installation of the Automation Kit based on [Install Instructions](https://learn.microsoft.com/power-automate/guidance/automation-kit/setup/main)

### Describe the solution you'd like

Provide the ability to:
1. Download the latest release from GitHub Releases
2. Authenticate with pac cli

```pswh
pac auth create -u https://contoso-org.crm.dynamics.com
```

3. Import the packge using the command line. For example
```
pac package deploy --logFile c:\samplelogdata --package c:\samplepackage
```

After deployment the following:
1. Creator Kit Is installed
2. Main or Satellite solutions are deployed
3. Connection references configured
4. Cloud Flows enabled
5. Optional install of sample data

### Additional context?

Provide optional commands to 
1. Provide connection id for required connection references
6. Provide optional install of sample data. Related to #19

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.
