### ISSUE TITLE
[Automation Kit - Feature]: New Field - Project Description

### ISSUE THREAD

**Issue by jpad5** [microsoft/powercat-automation-kit#83]
### Is your feature request related to a problem? Please describe.

Project Description is a common data field used to support the life cycle of the automation idea

### Describe the solution you'd like

A new data field added to "Project" intake screen.

**Comment by Grant-Archibald-MS** [comment]
@KoteshMCGit can this be included in the Feb release window. If not will need to be moved to March release window

**Comment by tnblackford** [comment]
If you add description field, please make it larger than 100 characters.

**Comment by KoteshMCGit** [comment]
As per Analysis, we need to create this new column Project Description in only main solution only.

screenshot of added new column project description (300 chars) to Automation Project table

![image](https://user-images.githubusercontent.com/107620140/221834461-386d915b-35f5-4957-9e14-b7c03416b038.png)

screenshot of project description column on UI
![image](https://user-images.githubusercontent.com/107620140/221835209-e249a639-a4f6-4c30-b838-41e83b0d25f6.png)

**Comment by KoteshMCGit** [comment]
Now modified from 300 to 500 chars.

**Comment by mikefactorial** [comment]
@jpad5 This has been fixed in the latest release.
