### ISSUE TITLE
[Automation Kit - Feature]: Azure Key Vault alternative for Satellite environments

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#84]
### Is your feature request related to a problem? Please describe.

Currently require Azure Key Vault as part of [Prerequisites](https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/setup/prerequisites#azure-key-vault) and [Satellite Environment Setup](https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/setup/satellite). Could investigation be done to provide alternative that does not require the client id and secret to be stored in Azure Key Vault so users that do not have access to an Azure Key Vault?

### Describe the solution you'd like

Provide an alternative method to authenticate as the Application User that does not require a Client Id and Secret to be stored in Azure Key Vault.

**Comment by Grant-Archibald-MS** [comment]
Investigation underway. Options being considered to make use of Power Platform Connector to Dataverse API so that the Client Id and Secret do not need to be stored in Key Vault.

If this change is made Satellite environments will no longer need a Key Vault instance to store the environment variables of type secret

**Comment by Grant-Archibald-MS** [comment]
Moving to Feb milestone to align with dependent platform feature rollout

**Comment by KoteshMCGit** [comment]
Find the below high level steps / design approach to pull solution components without using of Azure key vaults.

1. create one new custom API, to pull solution components from Dataverse msdyn_solutioncomponentsummarie with using of azure app user id as impersonate user for logged user
2. Create a new empty Dataverse table GetDataverseSolutionArtifacts, used to set read permissions to provide security to custom API.
3. Create a new security group "Automation Solution Manager User" to have read permission on GetDataverseSolutionArtifacts
4. Create a new environment variable "autocoe_SolutionManagerArtifactsReadUserID", used to read system user id for azure app registration id. which is used to impersonate to pull solution components to meter solution.

screen shot of created environment variable "autocoe_SolutionManagerArtifactsReadUserID":
![image](https://user-images.githubusercontent.com/107620140/229782785-cff31b80-ffbc-492f-9eed-0f256dabb4f9.png)

screen shot of new custom API "Autocoe_GetSolutionArtifacts
![image](https://user-images.githubusercontent.com/107620140/229783187-920a3952-1fd0-44df-8774-c449848f4639.png)

screen shot of input parameter for above custom API 
![image](https://user-images.githubusercontent.com/107620140/229783518-e5a644e0-1210-40f3-8b47-e2da266cf7d4.png)

**Comment by Grant-Archibald-MS** [comment]
References from [get started guide](https://microsoft.github.io/powercat-automation-kit/get-started/satellite/)
