### ISSUE TITLE
[Automation Kit - Feature]: Starter Site Localization

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#94]
### Is your feature request related to a problem? Please describe.

Today the current starter site is in English only. For non English speakers that would like to be able to read the content in local language automated translations may provide better access to the content

### Describe the solution you'd like

Provide the stater site content, images and questions in the following languages:
- English (en-us)
- English (en-gb)
- Danish (da)
- Dutch (nl)
- French (fr)
- Italian (it)
- Korean (ko)
- Japanese (ja)
- Norwegian (nb)
- Polish (pl)
- Romanian (ro)
- Simplified Chinese (zn-hans)
- Spanish (es)
- Swedish (sv)

### Additional context?

Connect this with Documentation packs that allow content from Automation Kit to be imported into my organization with different languages so that I can create localized content for regional teams.

**Comment by Grant-Archibald-MS** [comment]
Related to #16 and #35 to provide end to end localization of the report and data entry applications.

**Comment by Grant-Archibald-MS** [comment]
Initial work in progress version of the starter site that provides Azure Cognitive Service translation of the starter site content has started for the following:

[Danish](https://microsoft.github.io/powercat-automation-kit/da/)
[Dutch](https://microsoft.github.io/powercat-automation-kit/nl/)
[French](https://microsoft.github.io/powercat-automation-kit/fr/)
[Italian](https://microsoft.github.io/powercat-automation-kit/it/)
[Korean](https://microsoft.github.io/powercat-automation-kit/ko/)
[Japanese](https://microsoft.github.io/powercat-automation-kit/ja/)
[Norwegian](https://microsoft.github.io/powercat-automation-kit/nb/)
[Polish](https://microsoft.github.io/powercat-automation-kit/pl/)
[Spanish](https://microsoft.github.io/powercat-automation-kit/es/)
[Swedish](https://microsoft.github.io/powercat-automation-kit/sv/)

**Comment by Grant-Archibald-MS** [comment]
Updates to the site to allow per site localization to 
1. Add Site parameters with localized term
2. Localized questions

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.
