### ISSUE TITLE
[Automation Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by mabaugh83** [microsoft/powercat-automation-kit#95]
### What is your question?

We already have the Power Platform COE deployed. Can this be deployed in same Power Platform Environment or should it be standalone? 

The same team manages all of Power Platform so would make it easier to use one environment but want to make sure no conflicts :)

**Comment by Grant-Archibald-MS** [comment]
@mabaugh83 yes, they can be installed in the same environment as they used a different publisher prefix and use different dataverse tables.

**Comment by mabaugh83** [comment]
appreciate the response excellent news

**Comment by mikefactorial** [comment]
@mabaugh83 This has been fixed in the latest release.

**Comment by mabaugh83** [comment]
excellent news - thank you
