### ISSUE TITLE
[Automation - BUG] Approvals Workflow - Spelling Mistake

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#97]
### Describe the issue

https://github.com/microsoft/powercat-automation-kit/blob/main/AutomationCoEMain/SolutionPackage/src/Workflows/AutomationProject-Approvals-FEFEC70D-BF3C-EC11-B6E5-00224805CC2D.json

Includes title Improvment Driver

### Expected Behavior

Title should be Improvement Driver

### What component are you experiencing the issue with?

Cloud flows

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

Approval Workflow

### Steps To Reproduce

1,. Submit new project for Approval
2. Created Approval workflow has incorrect spelling

**Comment by KoteshMCGit** [comment]
issue has been fixed and verified.

**Comment by mikefactorial** [comment]
@Grant-Archibald-MS This has been fixed in the latest release.
