### ISSUE TITLE
[Automation - BUG] Missing CSV File

### ISSUE THREAD

**Issue by nasilvae** [microsoft/powercat-automation-kit#98]
### Describe the issue

The autocode_desktopflowactions.csv is not inside the release. This file is needed to complete the setup process. 

### Expected Behavior

CSV file to be inside the zip file. 

### What component are you experiencing the issue with?

Automation Center

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

CSV File

### Steps To Reproduce

File Missing. Video says there is a tools folder but I am unable to find it. https://www.youtube.com/watch?v=sB9iwzL3rYs

**Comment by mikefactorial** [comment]
@nasilvae This has been fixed in the latest release.

**Comment by nasilvae** [comment]
> @nasilvae This has been fixed in the latest release.

I am having issues finding it in the December release. Do we have another release that will have this fix?
